services:
  - type: web
    name: ibishop
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push && node prisma/seed.mjs && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: ADMIN_PASSWORD
        value: ibishop2026
      - key: NODE_VERSION
        value: 20.18.0
