import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const WILAYAS = [
  { id: 1, name: 'أدرار', price: 800, priceOffice: 600 },
  { id: 2, name: 'الشلف', price: 500, priceOffice: 400 },
  { id: 3, name: 'الأغواط', price: 700, priceOffice: 500 },
  { id: 4, name: 'أم البواقي', price: 500, priceOffice: 400 },
  { id: 5, name: 'باتنة', price: 500, priceOffice: 400 },
  { id: 6, name: 'بجاية', price: 400, priceOffice: 300 },
  { id: 7, name: 'بسكرة', price: 700, priceOffice: 500 },
  { id: 8, name: 'بشار', price: 900, priceOffice: 700 },
  { id: 9, name: 'البليدة', price: 300, priceOffice: 200 },
  { id: 10, name: 'البويرة', price: 400, priceOffice: 300 },
  { id: 11, name: 'تمنراست', price: 1200, priceOffice: 900 },
  { id: 12, name: 'تبسة', price: 600, priceOffice: 500 },
  { id: 13, name: 'تلمسان', price: 600, priceOffice: 500 },
  { id: 14, name: 'تيارت', price: 600, priceOffice: 500 },
  { id: 15, name: 'تيزي وزو', price: 400, priceOffice: 300 },
  { id: 16, name: 'الجزائر', price: 300, priceOffice: 200 },
  { id: 17, name: 'الجلفة', price: 600, priceOffice: 500 },
  { id: 18, name: 'جيجل', price: 500, priceOffice: 400 },
  { id: 19, name: 'سطيف', price: 400, priceOffice: 300 },
  { id: 20, name: 'سعيدة', price: 600, priceOffice: 500 },
  { id: 21, name: 'سكيكدة', price: 500, priceOffice: 400 },
  { id: 22, name: 'سيدي بلعباس', price: 600, priceOffice: 500 },
  { id: 23, name: 'عنابة', price: 500, priceOffice: 400 },
  { id: 24, name: 'قالمة', price: 500, priceOffice: 400 },
  { id: 25, name: 'قسنطينة', price: 500, priceOffice: 400 },
  { id: 26, name: 'المدية', price: 400, priceOffice: 300 },
  { id: 27, name: 'مستغانم', price: 500, priceOffice: 400 },
  { id: 28, name: 'المسيلة', price: 600, priceOffice: 500 },
  { id: 29, name: 'معسكر', price: 600, priceOffice: 500 },
  { id: 30, name: 'ورقلة', price: 800, priceOffice: 600 },
  { id: 31, name: 'وهران', price: 500, priceOffice: 400 },
  { id: 32, name: 'البيض', price: 800, priceOffice: 600 },
  { id: 33, name: 'إليزي', price: 1200, priceOffice: 900 },
  { id: 34, name: 'برج بوعريريج', price: 500, priceOffice: 400 },
  { id: 35, name: 'بومرداس', price: 300, priceOffice: 200 },
  { id: 36, name: 'الطارف', price: 600, priceOffice: 500 },
  { id: 37, name: 'تيندوف', price: 1200, priceOffice: 900 },
  { id: 38, name: 'تيسمسيلت', price: 500, priceOffice: 400 },
  { id: 39, name: 'الوادي', price: 700, priceOffice: 500 },
  { id: 40, name: 'خنشلة', price: 600, priceOffice: 500 },
  { id: 41, name: 'سوق أهراس', price: 600, priceOffice: 500 },
  { id: 42, name: 'تيبازة', price: 300, priceOffice: 200 },
  { id: 43, name: 'ميلة', price: 500, priceOffice: 400 },
  { id: 44, name: 'عين الدفلى', price: 400, priceOffice: 300 },
  { id: 45, name: 'النعامة', price: 700, priceOffice: 500 },
  { id: 46, name: 'عين تيموشنت', price: 500, priceOffice: 400 },
  { id: 47, name: 'غرداية', price: 700, priceOffice: 500 },
  { id: 48, name: 'غليزان', price: 500, priceOffice: 400 },
  { id: 49, name: 'Timimoun', price: 1000, priceOffice: 800 },
  { id: 50, name: 'Bordj Badji Mokhtar', price: 1400, priceOffice: 1100 },
  { id: 51, name: 'Ouled Djellal', price: 800, priceOffice: 600 },
  { id: 52, name: 'Béni Abbès', price: 1000, priceOffice: 800 },
  { id: 53, name: 'In Salah', price: 1300, priceOffice: 1000 },
  { id: 54, name: 'In Guezzam', price: 1500, priceOffice: 1200 },
  { id: 55, name: 'Touggourt', price: 800, priceOffice: 600 },
  { id: 56, name: 'Djanet', price: 1400, priceOffice: 1100 },
  { id: 57, name: "El M'Ghair", price: 700, priceOffice: 500 },
  { id: 58, name: 'El Meniaa', price: 900, priceOffice: 700 },
];

const COMMUNES = [
  { name: 'أدرار', wilayaId: 1 },
  { name: 'إن زغمير', wilayaId: 1 },
  { name: 'أوقروت', wilayaId: 1 },
  { name: 'أولاد أحمد تيمي', wilayaId: 1 },
  { name: 'أولاد السعيد', wilayaId: 1 },
  { name: 'أولاد عيسى', wilayaId: 1 },
  { name: 'أولف', wilayaId: 1 },
  { name: 'اقبلي', wilayaId: 1 },
  { name: 'السبع', wilayaId: 1 },
  { name: 'المطارفة', wilayaId: 1 },
  { name: 'برج باجي مختار', wilayaId: 1 },
  { name: 'بودة', wilayaId: 1 },
  { name: 'تامست', wilayaId: 1 },
  { name: 'تامنطيط', wilayaId: 1 },
  { name: 'تسابيت', wilayaId: 1 },
  { name: 'تنركوك', wilayaId: 1 },
  { name: 'تيت', wilayaId: 1 },
  { name: 'تيمقتن', wilayaId: 1 },
  { name: 'تيمياوين', wilayaId: 1 },
  { name: 'تيميمون', wilayaId: 1 },
  { name: 'دلدول', wilayaId: 1 },
  { name: 'رقان', wilayaId: 1 },
  { name: 'زاوية كنتة', wilayaId: 1 },
  { name: 'سالي', wilayaId: 1 },
  { name: 'شروين', wilayaId: 1 },
  { name: 'طالمين', wilayaId: 1 },
  { name: 'فنوغيل', wilayaId: 1 },
  { name: 'قصر قدور', wilayaId: 1 },
  { name: 'إن أميناس', wilayaId: 33 },
  { name: 'إيليزي', wilayaId: 33 },
  { name: 'برج الحواس', wilayaId: 33 },
  { name: 'برج عمر إدريس', wilayaId: 33 },
  { name: 'جانت', wilayaId: 33 },
  { name: 'دبداب', wilayaId: 33 },
  { name: 'أم البواقي', wilayaId: 4 },
  { name: 'أولاد حملة', wilayaId: 4 },
  { name: 'أولاد زواي', wilayaId: 4 },
  { name: 'أولاد قاسم', wilayaId: 4 },
  { name: 'البلالة', wilayaId: 4 },
  { name: 'الجازية', wilayaId: 4 },
  { name: 'الحرملية', wilayaId: 4 },
  { name: 'الرحية', wilayaId: 4 },
  { name: 'الزرق', wilayaId: 4 },
  { name: 'الضلعة', wilayaId: 4 },
  { name: 'العامرية', wilayaId: 4 },
  { name: 'الفجوج بوغرارة سعودي', wilayaId: 4 },
  { name: 'بئر الشهداء', wilayaId: 4 },
  { name: 'بحير الشرقي', wilayaId: 4 },
  { name: 'بريش', wilayaId: 4 },
  { name: 'سوق نعمان', wilayaId: 4 },
  { name: 'سيقوس', wilayaId: 4 },
  { name: 'عين البيضاء', wilayaId: 4 },
  { name: 'عين الديس', wilayaId: 4 },
  { name: 'عين الزيتون', wilayaId: 4 },
  { name: 'عين ببوش', wilayaId: 4 },
  { name: 'عين فكرون', wilayaId: 4 },
  { name: 'عين كرشة', wilayaId: 4 },
  { name: 'عين مليلة', wilayaId: 4 },
  { name: 'فكيرينة', wilayaId: 4 },
  { name: 'قصر الصباحي', wilayaId: 4 },
  { name: 'مسكيانة', wilayaId: 4 },
  { name: 'هنشير تومغني', wilayaId: 4 },
  { name: 'وادي نيني', wilayaId: 4 },
  { name: 'أفلو', wilayaId: 3 },
  { name: 'الأغواط', wilayaId: 3 },
  { name: 'البيضاء', wilayaId: 3 },
  { name: 'الحاج مشري', wilayaId: 3 },
  { name: 'الحويطة', wilayaId: 3 },
  { name: 'الخنق', wilayaId: 3 },
  { name: 'العسافية', wilayaId: 3 },
  { name: 'الغيشة', wilayaId: 3 },
  { name: 'بريدة', wilayaId: 3 },
  { name: 'بن ناصر بن شهرة', wilayaId: 3 },
  { name: 'تاجرونة', wilayaId: 3 },
  { name: 'تاجموت', wilayaId: 3 },
  { name: 'تاويالة', wilayaId: 3 },
  { name: 'حاسي الدلاعة', wilayaId: 3 },
  { name: 'حاسي الرمل', wilayaId: 3 },
  { name: 'سبقاق', wilayaId: 3 },
  { name: 'سيدي بوزيد', wilayaId: 3 },
  { name: 'سيدي مخلوف', wilayaId: 3 },
  { name: 'عين سيدي علي', wilayaId: 3 },
  { name: 'عين ماضي', wilayaId: 3 },
  { name: 'قصر الحيران', wilayaId: 3 },
  { name: 'قلتة سيدي سعيد', wilayaId: 3 },
  { name: 'وادي مرة', wilayaId: 3 },
  { name: 'وادي مزي', wilayaId: 3 },
  { name: 'أولاد يعيش', wilayaId: 9 },
  { name: 'الأربعاء', wilayaId: 9 },
  { name: 'البليدة', wilayaId: 9 },
  { name: 'الشبلي', wilayaId: 9 },
  { name: 'الشريعة', wilayaId: 9 },
  { name: 'الشفة', wilayaId: 9 },
  { name: 'الصومعة', wilayaId: 9 },
  { name: 'العفرون', wilayaId: 9 },
  { name: 'اولاد سلامة', wilayaId: 9 },
  { name: 'بن خليل', wilayaId: 9 },
  { name: 'بني تامو', wilayaId: 9 },
  { name: 'بني مراد', wilayaId: 9 },
  { name: 'بوعرفة', wilayaId: 9 },
  { name: 'بوعينان', wilayaId: 9 },
  { name: 'بوفاريك', wilayaId: 9 },
  { name: 'بوقرة', wilayaId: 9 },
  { name: 'جبابرة', wilayaId: 9 },
  { name: 'حمام ملوان', wilayaId: 9 },
  { name: 'سوحان', wilayaId: 9 },
  { name: 'عين الرمانة', wilayaId: 9 },
  { name: 'قرواو', wilayaId: 9 },
  { name: 'مفتاح', wilayaId: 9 },
  { name: 'موزاية', wilayaId: 9 },
  { name: 'وادي العلايق', wilayaId: 9 },
  { name: 'وادي جر', wilayaId: 9 },
  { name: 'آث منصور', wilayaId: 10 },
  { name: 'أعمر', wilayaId: 10 },
  { name: 'أغبالو', wilayaId: 10 },
  { name: 'أهل القصر', wilayaId: 10 },
  { name: 'أولاد راشد', wilayaId: 10 },
  { name: 'أيت لعزيز', wilayaId: 10 },
  { name: 'الأخضرية', wilayaId: 10 },
  { name: 'الأسنام', wilayaId: 10 },
  { name: 'البويرة', wilayaId: 10 },
  { name: 'الحاكمية', wilayaId: 10 },
  { name: 'الحجرة الزرقاء', wilayaId: 10 },
  { name: 'الحيزر', wilayaId: 10 },
  { name: 'الخبوزية', wilayaId: 10 },
  { name: 'الدشمية', wilayaId: 10 },
  { name: 'الشرفاء', wilayaId: 10 },
  { name: 'العجيبة', wilayaId: 10 },
  { name: 'القادرية', wilayaId: 10 },
  { name: 'المعمورة', wilayaId: 10 },
  { name: 'المقراني', wilayaId: 10 },
  { name: 'الهاشمية', wilayaId: 10 },
  { name: 'بئر غبالو', wilayaId: 10 },
  { name: 'برج أوخريص', wilayaId: 10 },
  { name: 'بشلول', wilayaId: 10 },
  { name: 'بودربالة', wilayaId: 10 },
  { name: 'بوكرم', wilayaId: 10 },
  { name: 'تاغزوت', wilayaId: 10 },
  { name: 'تاقديت', wilayaId: 10 },
  { name: 'جباحية', wilayaId: 10 },
  { name: 'حنيف', wilayaId: 10 },
  { name: 'ديرة', wilayaId: 10 },
  { name: 'روراوة', wilayaId: 10 },
  { name: 'ريدان', wilayaId: 10 },
  { name: 'زبربر', wilayaId: 10 },
  { name: 'سحاريج', wilayaId: 10 },
  { name: 'سور الغزلان', wilayaId: 10 },
  { name: 'سوق الخميس', wilayaId: 10 },
  { name: 'عين الترك', wilayaId: 10 },
  { name: 'عين الحجر', wilayaId: 10 },
  { name: 'عين العلوي', wilayaId: 10 },
  { name: 'عين بسام', wilayaId: 10 },
  { name: 'قرومة', wilayaId: 10 },
  { name: 'مزدور', wilayaId: 10 },
  { name: 'مشد الله', wilayaId: 10 },
  { name: 'معلة', wilayaId: 10 },
  { name: 'وادي البردي', wilayaId: 10 },
  { name: 'اربوات', wilayaId: 32 },
  { name: 'الأبيض سيدي الشيخ', wilayaId: 32 },
  { name: 'البنود', wilayaId: 32 },
  { name: 'البيض', wilayaId: 32 },
  { name: 'الخيثر', wilayaId: 32 },
  { name: 'الغاسول', wilayaId: 32 },
  { name: 'الكاف الأحمر', wilayaId: 32 },
  { name: 'المحرة', wilayaId: 32 },
  { name: 'بريزينة', wilayaId: 32 },
  { name: 'بوسمغون', wilayaId: 32 },
  { name: 'بوعلام', wilayaId: 32 },
  { name: 'بوقطب', wilayaId: 32 },
  { name: 'توسمولين', wilayaId: 32 },
  { name: 'رقاصة', wilayaId: 32 },
  { name: 'ستيتن', wilayaId: 32 },
  { name: 'سيدي سليمان', wilayaId: 32 },
  { name: 'سيدي طيفور', wilayaId: 32 },
  { name: 'سيدي عمر', wilayaId: 32 },
  { name: 'شلالة', wilayaId: 32 },
  { name: 'عين العراك', wilayaId: 32 },
  { name: 'كراكدة', wilayaId: 32 },
  { name: 'ابن عكنون', wilayaId: 16 },
  { name: 'الابيار', wilayaId: 16 },
  { name: 'الجزائر الوسطى', wilayaId: 16 },
  { name: 'الحراش', wilayaId: 16 },
  { name: 'الحمامات', wilayaId: 16 },
  { name: 'الخرايسية', wilayaId: 16 },
  { name: 'الدار البيضاء', wilayaId: 16 },
  { name: 'الدرارية', wilayaId: 16 },
  { name: 'الدويرة', wilayaId: 16 },
  { name: 'الرايس حميدو', wilayaId: 16 },
  { name: 'الرحمانية', wilayaId: 16 },
  { name: 'الرويبة', wilayaId: 16 },
  { name: 'السحاولة', wilayaId: 16 },
  { name: 'الشراقة', wilayaId: 16 },
  { name: 'العاشور', wilayaId: 16 },
  { name: 'القبة', wilayaId: 16 },
  { name: 'القصبة', wilayaId: 16 },
  { name: 'الكاليتوس', wilayaId: 16 },
  { name: 'المحمدية', wilayaId: 16 },
  { name: 'المدنية', wilayaId: 16 },
  { name: 'المرادية', wilayaId: 16 },
  { name: 'المرسى', wilayaId: 16 },
  { name: 'المعالمة', wilayaId: 16 },
  { name: 'المغارية', wilayaId: 16 },
  { name: 'اولاد شبل', wilayaId: 16 },
  { name: 'اولاد فايت', wilayaId: 16 },
  { name: 'بئر توتة', wilayaId: 16 },
  { name: 'بئر خادم', wilayaId: 16 },
  { name: 'بئر مراد رايس', wilayaId: 16 },
  { name: 'باب الزوار', wilayaId: 16 },
  { name: 'باب الوادي', wilayaId: 16 },
  { name: 'بابا حسن', wilayaId: 16 },
  { name: 'باش جراح', wilayaId: 16 },
  { name: 'براقي', wilayaId: 16 },
  { name: 'برج البحري', wilayaId: 16 },
  { name: 'برج الكيفان', wilayaId: 16 },
  { name: 'بني مسوس', wilayaId: 16 },
  { name: 'بوروبة', wilayaId: 16 },
  { name: 'بوزريعة', wilayaId: 16 },
  { name: 'بولوغين بن زيري', wilayaId: 16 },
  { name: 'تسالة المرجة', wilayaId: 16 },
  { name: 'جسر قسنطينة', wilayaId: 16 },
  { name: 'حسين داي', wilayaId: 16 },
  { name: 'حيدرة', wilayaId: 16 },
  { name: 'دالي ابراهيم', wilayaId: 16 },
  { name: 'رغاية', wilayaId: 16 },
  { name: 'زرالدة', wilayaId: 16 },
  { name: 'سطاوالي', wilayaId: 16 },
  { name: 'سويدانية', wilayaId: 16 },
  { name: 'سيدي امحمد', wilayaId: 16 },
  { name: 'سيدي موسى', wilayaId: 16 },
  { name: 'عين بنيان', wilayaId: 16 },
  { name: 'عين طاية', wilayaId: 16 },
  { name: 'محمد بلوزداد', wilayaId: 16 },
  { name: 'هراوة', wilayaId: 16 },
  { name: 'وادي السمار', wilayaId: 16 },
  { name: 'وادي قريش', wilayaId: 16 },
  { name: 'أم العظام', wilayaId: 17 },
  { name: 'الادريسية', wilayaId: 17 },
  { name: 'الجلفة', wilayaId: 17 },
  { name: 'الخميس', wilayaId: 17 },
  { name: 'الشارف', wilayaId: 17 },
  { name: 'القديد', wilayaId: 17 },
  { name: 'القطارة', wilayaId: 17 },
  { name: 'بنهار', wilayaId: 17 },
  { name: 'بني يعقوب', wilayaId: 17 },
  { name: 'بويرة الأحدب', wilayaId: 17 },
  { name: 'بيرين', wilayaId: 17 },
  { name: 'تاعظميت', wilayaId: 17 },
  { name: 'حاسي العش', wilayaId: 17 },
  { name: 'حاسي بحبح', wilayaId: 17 },
  { name: 'حاسي فدول', wilayaId: 17 },
  { name: 'حد الصحاري', wilayaId: 17 },
  { name: 'دار الشيوخ', wilayaId: 17 },
  { name: 'دلدول', wilayaId: 17 },
  { name: 'دويس', wilayaId: 17 },
  { name: 'زعفران', wilayaId: 17 },
  { name: 'زكار', wilayaId: 17 },
  { name: 'سد الرحال', wilayaId: 17 },
  { name: 'سلمانة', wilayaId: 17 },
  { name: 'سيدي بايزيد', wilayaId: 17 },
  { name: 'سيدي لعجال', wilayaId: 17 },
  { name: 'عمورة', wilayaId: 17 },
  { name: 'عين الإبل', wilayaId: 17 },
  { name: 'عين الشهداء', wilayaId: 17 },
  { name: 'عين فقه', wilayaId: 17 },
  { name: 'عين معبد', wilayaId: 17 },
  { name: 'عين وسارة', wilayaId: 17 },
  { name: 'فيض البطمة', wilayaId: 17 },
  { name: 'قرنيني', wilayaId: 17 },
  { name: 'مجبرة', wilayaId: 17 },
  { name: 'مسعد', wilayaId: 17 },
  { name: 'مليليحة', wilayaId: 17 },
  { name: 'أبو الحسن', wilayaId: 2 },
  { name: 'أم الدروع', wilayaId: 2 },
  { name: 'أولاد بن عبد القادر', wilayaId: 2 },
  { name: 'أولاد عباس', wilayaId: 2 },
  { name: 'أولاد فارس', wilayaId: 2 },
  { name: 'الأبيض مجاجة', wilayaId: 2 },
  { name: 'الحجاج', wilayaId: 2 },
  { name: 'الزبوجة', wilayaId: 2 },
  { name: 'الشطية', wilayaId: 2 },
  { name: 'الشلف', wilayaId: 2 },
  { name: 'الصبحة', wilayaId: 2 },
  { name: 'الظهرة', wilayaId: 2 },
  { name: 'الكريمية', wilayaId: 2 },
  { name: 'المرسى', wilayaId: 2 },
  { name: 'الهرانفة', wilayaId: 2 },
  { name: 'بريرة', wilayaId: 2 },
  { name: 'بنايرية', wilayaId: 2 },
  { name: 'بني بوعتاب', wilayaId: 2 },
  { name: 'بني حواء', wilayaId: 2 },
  { name: 'بني راشد', wilayaId: 2 },
  { name: 'بوزغاية', wilayaId: 2 },
  { name: 'بوقادير', wilayaId: 2 },
  { name: 'تاجنة', wilayaId: 2 },
  { name: 'تاوقريت', wilayaId: 2 },
  { name: 'تلعصة', wilayaId: 2 },
  { name: 'تنس', wilayaId: 2 },
  { name: 'حرشون', wilayaId: 2 },
  { name: 'سنجاس', wilayaId: 2 },
  { name: 'سيدي عبد الرحمن', wilayaId: 2 },
  { name: 'سيدي عكاشة', wilayaId: 2 },
  { name: 'عين مران', wilayaId: 2 },
  { name: 'مصدق', wilayaId: 2 },
  { name: 'وادي الفضة', wilayaId: 2 },
  { name: 'وادي سلي', wilayaId: 2 },
  { name: 'وادي قوسين', wilayaId: 2 },
  { name: 'ابن مهيدي', wilayaId: 36 },
  { name: 'البسباس', wilayaId: 36 },
  { name: 'الذرعـان', wilayaId: 36 },
  { name: 'الزيتونة', wilayaId: 36 },
  { name: 'السواريخ', wilayaId: 36 },
  { name: 'الشافية', wilayaId: 36 },
  { name: 'الشط', wilayaId: 36 },
  { name: 'الطارف', wilayaId: 36 },
  { name: 'العيون', wilayaId: 36 },
  { name: 'القالة', wilayaId: 36 },
  { name: 'بحيرة الطيور', wilayaId: 36 },
  { name: 'بريحان', wilayaId: 36 },
  { name: 'بوثلجة', wilayaId: 36 },
  { name: 'بوحجار', wilayaId: 36 },
  { name: 'بوقوس', wilayaId: 36 },
  { name: 'حمام بني صالح', wilayaId: 36 },
  { name: 'رمل السوق', wilayaId: 36 },
  { name: 'زريزر', wilayaId: 36 },
  { name: 'شبيطة مختار', wilayaId: 36 },
  { name: 'شحاني', wilayaId: 36 },
  { name: 'عصفور', wilayaId: 36 },
  { name: 'عين العسل', wilayaId: 36 },
  { name: 'عين الكرمة', wilayaId: 36 },
  { name: 'وادي الزيتون', wilayaId: 36 },
  { name: 'أم الجليل', wilayaId: 26 },
  { name: 'أولاد إبراهيم', wilayaId: 26 },
  { name: 'أولاد امعرف', wilayaId: 26 },
  { name: 'أولاد بوعشرة', wilayaId: 26 },
  { name: 'أولاد دايد', wilayaId: 26 },
  { name: 'أولاد عنتر', wilayaId: 26 },
  { name: 'أولاد هلال', wilayaId: 26 },
  { name: 'البرواقية', wilayaId: 26 },
  { name: 'الحمدانية', wilayaId: 26 },
  { name: 'الحوضان', wilayaId: 26 },
  { name: 'الربعية', wilayaId: 26 },
  { name: 'الزبيرية', wilayaId: 26 },
  { name: 'السانق', wilayaId: 26 },
  { name: 'السواقي', wilayaId: 26 },
  { name: 'الشهبونية', wilayaId: 26 },
  { name: 'العزيزية', wilayaId: 26 },
  { name: 'العمرية', wilayaId: 26 },
  { name: 'العوينات', wilayaId: 26 },
  { name: 'العيساوية', wilayaId: 26 },
  { name: 'القلب الكبير', wilayaId: 26 },
  { name: 'الكاف الاخضر', wilayaId: 26 },
  { name: 'المدية', wilayaId: 26 },
  { name: 'بئر بن عابد', wilayaId: 26 },
  { name: 'بعطة', wilayaId: 26 },
  { name: 'بن شكاو', wilayaId: 26 },
  { name: 'بني سليمان', wilayaId: 26 },
  { name: 'بوسكن', wilayaId: 26 },
  { name: 'بوشراحيل', wilayaId: 26 },
  { name: 'بوعيش', wilayaId: 26 },
  { name: 'بوعيشون', wilayaId: 26 },
  { name: 'بوغار', wilayaId: 26 },
  { name: 'بوغزول', wilayaId: 26 },
  { name: 'تابلاط', wilayaId: 26 },
  { name: 'تفراوت', wilayaId: 26 },
  { name: 'تمسقيدة', wilayaId: 26 },
  { name: 'تيزي مهدي', wilayaId: 26 },
  { name: 'ثلاث دوائر', wilayaId: 26 },
  { name: 'جواب', wilayaId: 26 },
  { name: 'حناشة', wilayaId: 26 },
  { name: 'خمس جوامع', wilayaId: 26 },
  { name: 'دراق', wilayaId: 26 },
  { name: 'ذراع السمار', wilayaId: 26 },
  { name: 'سدراية', wilayaId: 26 },
  { name: 'سغوان', wilayaId: 26 },
  { name: 'سي المحجوب', wilayaId: 26 },
  { name: 'سيدي الربيع', wilayaId: 26 },
  { name: 'سيدي دامد', wilayaId: 26 },
  { name: 'سيدي زهار', wilayaId: 26 },
  { name: 'سيدي زيان', wilayaId: 26 },
  { name: 'سيدي نعمان', wilayaId: 26 },
  { name: 'شلالة العذاورة', wilayaId: 26 },
  { name: 'شنيقل', wilayaId: 26 },
  { name: 'عزيز', wilayaId: 26 },
  { name: 'عوامري', wilayaId: 26 },
  { name: 'عين اقصير', wilayaId: 26 },
  { name: 'عين بوسيف', wilayaId: 26 },
  { name: 'قصر البخاري', wilayaId: 26 },
  { name: 'مجبر', wilayaId: 26 },
  { name: 'مزغنة', wilayaId: 26 },
  { name: 'مغراوة', wilayaId: 26 },
  { name: 'مفاتحة', wilayaId: 26 },
  { name: 'ميهوب', wilayaId: 26 },
  { name: 'وادي حربيل', wilayaId: 26 },
  { name: 'وزرة', wilayaId: 26 },
  { name: 'أولاد دراج', wilayaId: 28 },
  { name: 'أولاد سليمان', wilayaId: 28 },
  { name: 'أولاد سيدي ابراهيم', wilayaId: 28 },
  { name: 'أولاد عدي قبالة', wilayaId: 28 },
  { name: 'أولاد ماضي', wilayaId: 28 },
  { name: 'أولاد منصور', wilayaId: 28 },
  { name: 'ابن سرور', wilayaId: 28 },
  { name: 'الحوامد', wilayaId: 28 },
  { name: 'السوامع', wilayaId: 28 },
  { name: 'المسيلة', wilayaId: 28 },
  { name: 'المطارفة', wilayaId: 28 },
  { name: 'المعاضيد', wilayaId: 28 },
  { name: 'الهامل', wilayaId: 28 },
  { name: 'بئر الفضة', wilayaId: 28 },
  { name: 'برهوم', wilayaId: 28 },
  { name: 'بلعايبة', wilayaId: 28 },
  { name: 'بن زوه', wilayaId: 28 },
  { name: 'بني يلمان', wilayaId: 28 },
  { name: 'بوسعادة', wilayaId: 28 },
  { name: 'بوطي السياح', wilayaId: 28 },
  { name: 'تارمونت', wilayaId: 28 },
  { name: 'تامسة', wilayaId: 28 },
  { name: 'جبل مساعد', wilayaId: 28 },
  { name: 'حمام الضلعة', wilayaId: 28 },
  { name: 'خبانة', wilayaId: 28 },
  { name: 'ختوتي سد الجير', wilayaId: 28 },
  { name: 'دهاهنة', wilayaId: 28 },
  { name: 'زرزور', wilayaId: 28 },
  { name: 'سليم', wilayaId: 28 },
  { name: 'سيدي أمحمد', wilayaId: 28 },
  { name: 'سيدي عامر', wilayaId: 28 },
  { name: 'سيدي عيسى', wilayaId: 28 },
  { name: 'سيدي هجرس', wilayaId: 28 },
  { name: 'شلال', wilayaId: 28 },
  { name: 'عين الحجل', wilayaId: 28 },
  { name: 'عين الريش', wilayaId: 28 },
  { name: 'عين الملح', wilayaId: 28 },
  { name: 'عين خضراء', wilayaId: 28 },
  { name: 'عين فارس', wilayaId: 28 },
  { name: 'مجدل', wilayaId: 28 },
  { name: 'محمد بوضياف', wilayaId: 28 },
  { name: 'مسيف', wilayaId: 28 },
  { name: 'معاريف', wilayaId: 28 },
  { name: 'مقرة', wilayaId: 28 },
  { name: 'منعة -أولاد عطية', wilayaId: 28 },
  { name: 'ولتام', wilayaId: 28 },
  { name: 'ونوغة', wilayaId: 28 },
  { name: 'البيوض', wilayaId: 45 },
  { name: 'القصدير', wilayaId: 45 },
  { name: 'المشرية', wilayaId: 45 },
  { name: 'النعامة', wilayaId: 45 },
  { name: 'تيوت', wilayaId: 45 },
  { name: 'جنين بورزق', wilayaId: 45 },
  { name: 'صفيصيفة', wilayaId: 45 },
  { name: 'عسلة', wilayaId: 45 },
  { name: 'عين الصفراء', wilayaId: 45 },
  { name: 'عين بن خليل', wilayaId: 45 },
  { name: 'مغرار', wilayaId: 45 },
  { name: 'مكمن بن عمار', wilayaId: 45 },
  { name: 'أم الطيور', wilayaId: 39 },
  { name: 'البياضة', wilayaId: 39 },
  { name: 'الحمراية', wilayaId: 39 },
  { name: 'الدبيلة', wilayaId: 39 },
  { name: 'الرباح', wilayaId: 39 },
  { name: 'الرقيبة', wilayaId: 39 },
  { name: 'الطالب العربي', wilayaId: 39 },
  { name: 'الطريفاوي', wilayaId: 39 },
  { name: 'العقلة', wilayaId: 39 },
  { name: 'المرارة', wilayaId: 39 },
  { name: 'المغير', wilayaId: 39 },
  { name: 'المقرن', wilayaId: 39 },
  { name: 'النخلة', wilayaId: 39 },
  { name: 'الوادي', wilayaId: 39 },
  { name: 'اميه وانسة', wilayaId: 39 },
  { name: 'بن قشة', wilayaId: 39 },
  { name: 'تغزوت', wilayaId: 39 },
  { name: 'تندلة', wilayaId: 39 },
  { name: 'جامعة', wilayaId: 39 },
  { name: 'حاسي خليفة', wilayaId: 39 },
  { name: 'حساني عبد الكريم', wilayaId: 39 },
  { name: 'دوار الماء', wilayaId: 39 },
  { name: 'سطيل', wilayaId: 39 },
  { name: 'سيدي خليل', wilayaId: 39 },
  { name: 'سيدي عمران', wilayaId: 39 },
  { name: 'سيدي عون', wilayaId: 39 },
  { name: 'قمار', wilayaId: 39 },
  { name: 'كوينين', wilayaId: 39 },
  { name: 'وادي العلندة', wilayaId: 39 },
  { name: 'ورماس', wilayaId: 39 },
  { name: 'أريس', wilayaId: 5 },
  { name: 'إشمول', wilayaId: 5 },
  { name: 'إمدوكل', wilayaId: 5 },
  { name: 'أولاد سلام', wilayaId: 5 },
  { name: 'أولاد سي سليمان', wilayaId: 5 },
  { name: 'أولاد عمار', wilayaId: 5 },
  { name: 'أولاد عوف', wilayaId: 5 },
  { name: 'أولاد فاضل', wilayaId: 5 },
  { name: 'إينوغيسن', wilayaId: 5 },
  { name: 'الجزار', wilayaId: 5 },
  { name: 'الحاسي', wilayaId: 5 },
  { name: 'الرحبات', wilayaId: 5 },
  { name: 'الشمرة', wilayaId: 5 },
  { name: 'القصبات', wilayaId: 5 },
  { name: 'القيقبة', wilayaId: 5 },
  { name: 'المعذر', wilayaId: 5 },
  { name: 'باتنة', wilayaId: 5 },
  { name: 'بريكة', wilayaId: 5 },
  { name: 'بني فضالة الحقانية', wilayaId: 5 },
  { name: 'بوزينة', wilayaId: 5 },
  { name: 'بولهيلات', wilayaId: 5 },
  { name: 'بومقر', wilayaId: 5 },
  { name: 'بومية', wilayaId: 5 },
  { name: 'بيطام', wilayaId: 5 },
  { name: 'تازولت', wilayaId: 5 },
  { name: 'تاكسلانت', wilayaId: 5 },
  { name: 'تالخمت', wilayaId: 5 },
  { name: 'تغرغار', wilayaId: 5 },
  { name: 'تكوت', wilayaId: 5 },
  { name: 'تيغانمين', wilayaId: 5 },
  { name: 'تيلاطو', wilayaId: 5 },
  { name: 'تيمقاد', wilayaId: 5 },
  { name: 'ثنية العابد', wilayaId: 5 },
  { name: 'جرمة', wilayaId: 5 },
  { name: 'حيدوسة', wilayaId: 5 },
  { name: 'رأس العيون', wilayaId: 5 },
  { name: 'زانة البيضاء', wilayaId: 5 },
  { name: 'سريانة', wilayaId: 5 },
  { name: 'سفيان', wilayaId: 5 },
  { name: 'سقانة', wilayaId: 5 },
  { name: 'شير', wilayaId: 5 },
  { name: 'عزيل عبد القادر', wilayaId: 5 },
  { name: 'عين التوتة', wilayaId: 5 },
  { name: 'عين جاسر', wilayaId: 5 },
  { name: 'عين ياقوت', wilayaId: 5 },
  { name: 'عيون العصافير', wilayaId: 5 },
  { name: 'غسيرة', wilayaId: 5 },
  { name: 'فسديس', wilayaId: 5 },
  { name: 'فم الطوب', wilayaId: 5 },
  { name: 'قصر بلزمة', wilayaId: 5 },
  { name: 'كيمل', wilayaId: 5 },
  { name: 'لارباع', wilayaId: 5 },
  { name: 'لازرو', wilayaId: 5 },
  { name: 'لمسان', wilayaId: 5 },
  { name: 'مروانة', wilayaId: 5 },
  { name: 'معافة', wilayaId: 5 },
  { name: 'منعة', wilayaId: 5 },
  { name: 'نقاوس', wilayaId: 5 },
  { name: 'وادي الشعبة', wilayaId: 5 },
  { name: 'وادي الطاقة', wilayaId: 5 },
  { name: 'وادي الماء', wilayaId: 5 },
  { name: 'أدكار', wilayaId: 6 },
  { name: 'إغيل علي', wilayaId: 6 },
  { name: 'أقبو', wilayaId: 6 },
  { name: 'أكفادو', wilayaId: 6 },
  { name: 'أمالو', wilayaId: 6 },
  { name: 'أميزور', wilayaId: 6 },
  { name: 'أوقاس', wilayaId: 6 },
  { name: 'أيت إسماعيل', wilayaId: 6 },
  { name: 'أيت رزين', wilayaId: 6 },
  { name: 'اغرام', wilayaId: 6 },
  { name: 'الفلاي', wilayaId: 6 },
  { name: 'القصر', wilayaId: 6 },
  { name: 'اوزلقن', wilayaId: 6 },
  { name: 'بجاية', wilayaId: 6 },
  { name: 'برباشة', wilayaId: 6 },
  { name: 'بني جليل', wilayaId: 6 },
  { name: 'بني كسيلة', wilayaId: 6 },
  { name: 'بني معوش', wilayaId: 6 },
  { name: 'بني مليكش', wilayaId: 6 },
  { name: 'بو جليل', wilayaId: 6 },
  { name: 'بوحمزة', wilayaId: 6 },
  { name: 'بوخليفة', wilayaId: 6 },
  { name: 'تازملت', wilayaId: 6 },
  { name: 'تاسكريوت', wilayaId: 6 },
  { name: 'تالة حمزة', wilayaId: 6 },
  { name: 'تامريجت', wilayaId: 6 },
  { name: 'تاوريرت إغيل', wilayaId: 6 },
  { name: 'تمقرة', wilayaId: 6 },
  { name: 'توجة', wilayaId: 6 },
  { name: 'تيزي نبربر', wilayaId: 6 },
  { name: 'تيشي', wilayaId: 6 },
  { name: 'تيفرة', wilayaId: 6 },
  { name: 'تيمزريت', wilayaId: 6 },
  { name: 'تينبدار', wilayaId: 6 },
  { name: 'خراطة', wilayaId: 6 },
  { name: 'درقينة', wilayaId: 6 },
  { name: 'ذراع القايد', wilayaId: 6 },
  { name: 'سمعون', wilayaId: 6 },
  { name: 'سوق اوفله', wilayaId: 6 },
  { name: 'سوق لإثنين', wilayaId: 6 },
  { name: 'سيدي عياد', wilayaId: 6 },
  { name: 'سيدي عيش', wilayaId: 6 },
  { name: 'شلاطة', wilayaId: 6 },
  { name: 'شميني', wilayaId: 6 },
  { name: 'صدوق', wilayaId: 6 },
  { name: 'طيبان', wilayaId: 6 },
  { name: 'فرعون', wilayaId: 6 },
  { name: 'فناية الماتن', wilayaId: 6 },
  { name: 'كنديرة', wilayaId: 6 },
  { name: 'مالبو', wilayaId: 6 },
  { name: 'مسيسنة', wilayaId: 6 },
  { name: 'وادي غير', wilayaId: 6 },
  { name: 'أولاد أبراهم', wilayaId: 34 },
  { name: 'أولاد دحمان', wilayaId: 34 },
  { name: 'أولاد سيدي ابراهيم', wilayaId: 34 },
  { name: 'الحمادية', wilayaId: 34 },
  { name: 'الرابطة', wilayaId: 34 },
  { name: 'العش', wilayaId: 34 },
  { name: 'العناصر', wilayaId: 34 },
  { name: 'القصور', wilayaId: 34 },
  { name: 'القلة', wilayaId: 34 },
  { name: 'الماين', wilayaId: 34 },
  { name: 'المنصورة', wilayaId: 34 },
  { name: 'المهير', wilayaId: 34 },
  { name: 'الياشير', wilayaId: 34 },
  { name: 'بئر قاصد علي', wilayaId: 34 },
  { name: 'برج الغدير', wilayaId: 34 },
  { name: 'برج بوعريرج', wilayaId: 34 },
  { name: 'برج زمورة', wilayaId: 34 },
  { name: 'بليمور', wilayaId: 34 },
  { name: 'بن داود', wilayaId: 34 },
  { name: 'تسامرت', wilayaId: 34 },
  { name: 'تفرق', wilayaId: 34 },
  { name: 'تقلعيت', wilayaId: 34 },
  { name: 'تيكستار', wilayaId: 34 },
  { name: 'ثنية النصر', wilayaId: 34 },
  { name: 'جعافرة', wilayaId: 34 },
  { name: 'حرازة', wilayaId: 34 },
  { name: 'حسناوة', wilayaId: 34 },
  { name: 'خليل', wilayaId: 34 },
  { name: 'رأس الوادي', wilayaId: 34 },
  { name: 'سيدي أمبارك', wilayaId: 34 },
  { name: 'عين تاغروت', wilayaId: 34 },
  { name: 'عين تسرة', wilayaId: 34 },
  { name: 'غيلاسة', wilayaId: 34 },
  { name: 'مجانة', wilayaId: 34 },
  { name: 'أورلال', wilayaId: 7 },
  { name: 'أولاد جلال', wilayaId: 7 },
  { name: 'أوماش', wilayaId: 7 },
  { name: 'الحاجب', wilayaId: 7 },
  { name: 'الحوش', wilayaId: 7 },
  { name: 'الدوسن', wilayaId: 7 },
  { name: 'الشعيبة', wilayaId: 7 },
  { name: 'الغروس', wilayaId: 7 },
  { name: 'الفيض', wilayaId: 7 },
  { name: 'القنطرة', wilayaId: 7 },
  { name: 'المزيرعة', wilayaId: 7 },
  { name: 'الوطاية', wilayaId: 7 },
  { name: 'برانيس', wilayaId: 7 },
  { name: 'برج بن عزوز', wilayaId: 7 },
  { name: 'بسباس', wilayaId: 7 },
  { name: 'بسكرة', wilayaId: 7 },
  { name: 'بوشقرون', wilayaId: 7 },
  { name: 'جمورة', wilayaId: 7 },
  { name: 'خنقة سيدي ناجي', wilayaId: 7 },
  { name: 'رأس الميعاد', wilayaId: 7 },
  { name: 'زريبة الوادي', wilayaId: 7 },
  { name: 'سيدي خالد', wilayaId: 7 },
  { name: 'سيدي عقبة', wilayaId: 7 },
  { name: 'شتمة', wilayaId: 7 },
  { name: 'طولقة', wilayaId: 7 },
  { name: 'عين الناقة', wilayaId: 7 },
  { name: 'عين زعطوط', wilayaId: 7 },
  { name: 'فوغالة', wilayaId: 7 },
  { name: 'ليشانة', wilayaId: 7 },
  { name: 'ليوة', wilayaId: 7 },
  { name: 'مخادمة', wilayaId: 7 },
  { name: 'مشونش', wilayaId: 7 },
  { name: 'مليلي', wilayaId: 7 },
  { name: 'إقلي', wilayaId: 8 },
  { name: 'أولاد خضير', wilayaId: 8 },
  { name: 'العبادلة', wilayaId: 8 },
  { name: 'القصابي', wilayaId: 8 },
  { name: 'القنادسة', wilayaId: 8 },
  { name: 'المريجة', wilayaId: 8 },
  { name: 'الواتة', wilayaId: 8 },
  { name: 'بشار', wilayaId: 8 },
  { name: 'بني عباس', wilayaId: 8 },
  { name: 'بني ونيف', wilayaId: 8 },
  { name: 'بني يخلف', wilayaId: 8 },
  { name: 'بوكايس', wilayaId: 8 },
  { name: 'تاغيت', wilayaId: 8 },
  { name: 'تامترت', wilayaId: 8 },
  { name: 'تبلبالة', wilayaId: 8 },
  { name: 'تيمودي', wilayaId: 8 },
  { name: 'عرق فراج', wilayaId: 8 },
  { name: 'كرزاز', wilayaId: 8 },
  { name: 'لحمر', wilayaId: 8 },
  { name: 'مشرع هواري بومدين', wilayaId: 8 },
  { name: 'موغل', wilayaId: 8 },
  { name: 'أعفير', wilayaId: 35 },
  { name: 'أولاد عيسى', wilayaId: 35 },
  { name: 'أولاد موسى', wilayaId: 35 },
  { name: 'أولاد هداج', wilayaId: 35 },
  { name: 'الاربعطاش', wilayaId: 35 },
  { name: 'الثنية', wilayaId: 35 },
  { name: 'الخروبة', wilayaId: 35 },
  { name: 'الناصرية', wilayaId: 35 },
  { name: 'برج منايل', wilayaId: 35 },
  { name: 'بغلية', wilayaId: 35 },
  { name: 'بن شود', wilayaId: 35 },
  { name: 'بني عمران', wilayaId: 35 },
  { name: 'بودواو', wilayaId: 35 },
  { name: 'بودواو البحري', wilayaId: 35 },
  { name: 'بوزقزة قدارة', wilayaId: 35 },
  { name: 'بومرداس', wilayaId: 35 },
  { name: 'تاورقة', wilayaId: 35 },
  { name: 'تيجلابين', wilayaId: 35 },
  { name: 'تيمزريت', wilayaId: 35 },
  { name: 'جنات', wilayaId: 35 },
  { name: 'حمادي', wilayaId: 35 },
  { name: 'خميس الخشنة', wilayaId: 35 },
  { name: 'دلس', wilayaId: 35 },
  { name: 'زموري', wilayaId: 35 },
  { name: 'سوق الأحد', wilayaId: 35 },
  { name: 'سي مصطفى', wilayaId: 35 },
  { name: 'سيدي داود', wilayaId: 35 },
  { name: 'شعبة العامر', wilayaId: 35 },
  { name: 'عمال', wilayaId: 35 },
  { name: 'قورصو', wilayaId: 35 },
  { name: 'لقاطة', wilayaId: 35 },
  { name: 'يسر', wilayaId: 35 },
  { name: 'أم علي', wilayaId: 12 },
  { name: 'الحمامات', wilayaId: 12 },
  { name: 'الحويجبات', wilayaId: 12 },
  { name: 'الشريعة', wilayaId: 12 },
  { name: 'العقلة', wilayaId: 12 },
  { name: 'العقلة المالحة', wilayaId: 12 },
  { name: 'العوينات', wilayaId: 12 },
  { name: 'الكويف', wilayaId: 12 },
  { name: 'الماء الابيض', wilayaId: 12 },
  { name: 'المريج', wilayaId: 12 },
  { name: 'المزرعة', wilayaId: 12 },
  { name: 'الونزة', wilayaId: 12 },
  { name: 'بئر الذهب', wilayaId: 12 },
  { name: 'بئر العاتر', wilayaId: 12 },
  { name: 'بئر مقدم', wilayaId: 12 },
  { name: 'بجن', wilayaId: 12 },
  { name: 'بكارية', wilayaId: 12 },
  { name: 'بوخضرة', wilayaId: 12 },
  { name: 'بولحاف الدير', wilayaId: 12 },
  { name: 'تبسة', wilayaId: 12 },
  { name: 'ثليجان', wilayaId: 12 },
  { name: 'سطح قنطيس', wilayaId: 12 },
  { name: 'صفصاف الوسرى', wilayaId: 12 },
  { name: 'عين الزرقاء', wilayaId: 12 },
  { name: 'فركان', wilayaId: 12 },
  { name: 'قريقر', wilayaId: 12 },
  { name: 'مرسط', wilayaId: 12 },
  { name: 'نقرين', wilayaId: 12 },
  { name: 'إبن سكران', wilayaId: 13 },
  { name: 'أولاد رياح', wilayaId: 13 },
  { name: 'أولاد ميمون', wilayaId: 13 },
  { name: 'البويهي', wilayaId: 13 },
  { name: 'الحناية', wilayaId: 13 },
  { name: 'الرمشي', wilayaId: 13 },
  { name: 'السبعة شيوخ', wilayaId: 13 },
  { name: 'السواحلية', wilayaId: 13 },
  { name: 'السواني', wilayaId: 13 },
  { name: 'العريشة', wilayaId: 13 },
  { name: 'العزايل', wilayaId: 13 },
  { name: 'العين الكبيرة', wilayaId: 13 },
  { name: 'الغزوات', wilayaId: 13 },
  { name: 'الفحول', wilayaId: 13 },
  { name: 'القور', wilayaId: 13 },
  { name: 'باب العسة', wilayaId: 13 },
  { name: 'بني بهدل', wilayaId: 13 },
  { name: 'بني بوسعيد', wilayaId: 13 },
  { name: 'بني خلاد', wilayaId: 13 },
  { name: 'بني سنوس', wilayaId: 13 },
  { name: 'بني صميل', wilayaId: 13 },
  { name: 'بني مستر', wilayaId: 13 },
  { name: 'بني وارسوس', wilayaId: 13 },
  { name: 'بوحلو', wilayaId: 13 },
  { name: 'تلمسان', wilayaId: 13 },
  { name: 'تيانت', wilayaId: 13 },
  { name: 'تيرني بني هديل', wilayaId: 13 },
  { name: 'جبالة', wilayaId: 13 },
  { name: 'حمام بوغرارة', wilayaId: 13 },
  { name: 'حنين', wilayaId: 13 },
  { name: 'دار يغمراسن', wilayaId: 13 },
  { name: 'زناتة', wilayaId: 13 },
  { name: 'سبدو', wilayaId: 13 },
  { name: 'سوق الثلاثاء', wilayaId: 13 },
  { name: 'سيدي الجيلالي', wilayaId: 13 },
  { name: 'سيدي العبدلي', wilayaId: 13 },
  { name: 'سيدي مجاهد', wilayaId: 13 },
  { name: 'شتوان', wilayaId: 13 },
  { name: 'صبرة', wilayaId: 13 },
  { name: 'عمير', wilayaId: 13 },
  { name: 'عين الغرابة', wilayaId: 13 },
  { name: 'عين تالوت', wilayaId: 13 },
  { name: 'عين فتاح', wilayaId: 13 },
  { name: 'عين فزة', wilayaId: 13 },
  { name: 'عين نحالة', wilayaId: 13 },
  { name: 'عين يوسف', wilayaId: 13 },
  { name: 'فلاوسن', wilayaId: 13 },
  { name: 'مرسى بن مهيدي', wilayaId: 13 },
  { name: 'مسيردة الفواقة', wilayaId: 13 },
  { name: 'مغنية', wilayaId: 13 },
  { name: 'منصورة', wilayaId: 13 },
  { name: 'ندرومة', wilayaId: 13 },
  { name: 'وادي لخظر', wilayaId: 13 },
  { name: 'أدلس', wilayaId: 11 },
  { name: 'إينغر', wilayaId: 11 },
  { name: 'ابلسة', wilayaId: 11 },
  { name: 'تاظروك', wilayaId: 11 },
  { name: 'تمنراست', wilayaId: 11 },
  { name: 'تين زواتين', wilayaId: 11 },
  { name: 'عين امقل', wilayaId: 11 },
  { name: 'عين صالح', wilayaId: 11 },
  { name: 'عين قزام', wilayaId: 11 },
  { name: 'فقارة الزوى', wilayaId: 11 },
  { name: 'الحمادية', wilayaId: 14 },
  { name: 'الرشايقة', wilayaId: 14 },
  { name: 'السبت', wilayaId: 14 },
  { name: 'السوقر', wilayaId: 14 },
  { name: 'الفايجة', wilayaId: 14 },
  { name: 'الناظورة', wilayaId: 14 },
  { name: 'النعيمة', wilayaId: 14 },
  { name: 'بوقرة', wilayaId: 14 },
  { name: 'تاقدمت', wilayaId: 14 },
  { name: 'تخمرت', wilayaId: 14 },
  { name: 'توسنينة', wilayaId: 14 },
  { name: 'تيارت', wilayaId: 14 },
  { name: 'تيدة', wilayaId: 14 },
  { name: 'جبيلة الرصفاء', wilayaId: 14 },
  { name: 'جيلالي بن عمار', wilayaId: 14 },
  { name: 'دحموني', wilayaId: 14 },
  { name: 'رحوية', wilayaId: 14 },
  { name: 'زمالة الامير عبد القادر', wilayaId: 14 },
  { name: 'سبعين', wilayaId: 14 },
  { name: 'سرغين', wilayaId: 14 },
  { name: 'سي عبد الغني', wilayaId: 14 },
  { name: 'سيدي بختي', wilayaId: 14 },
  { name: 'سيدي حسني', wilayaId: 14 },
  { name: 'سيدي عبد الرحمن', wilayaId: 14 },
  { name: 'سيدي علي ملال', wilayaId: 14 },
  { name: 'شحيمة', wilayaId: 14 },
  { name: 'عين الحديد', wilayaId: 14 },
  { name: 'عين الذهب', wilayaId: 14 },
  { name: 'عين بوشقيف', wilayaId: 14 },
  { name: 'عين دزاريت', wilayaId: 14 },
  { name: 'عين كرمس', wilayaId: 14 },
  { name: 'فرندة', wilayaId: 14 },
  { name: 'قرطوفة', wilayaId: 14 },
  { name: 'قصر الشلالة', wilayaId: 14 },
  { name: 'مادنة', wilayaId: 14 },
  { name: 'مدروسة', wilayaId: 14 },
  { name: 'مدريسة', wilayaId: 14 },
  { name: 'مشرع الصفا', wilayaId: 14 },
  { name: 'مغيلة', wilayaId: 14 },
  { name: 'ملاكو', wilayaId: 14 },
  { name: 'مهدية', wilayaId: 14 },
  { name: 'وادي ليلي', wilayaId: 14 },
  { name: 'أحمر العين', wilayaId: 42 },
  { name: 'أغبال', wilayaId: 42 },
  { name: 'الأرهاط', wilayaId: 42 },
  { name: 'الحطاطبة', wilayaId: 42 },
  { name: 'الداموس', wilayaId: 42 },
  { name: 'الشعيبة', wilayaId: 42 },
  { name: 'القليعة', wilayaId: 42 },
  { name: 'الناظور', wilayaId: 42 },
  { name: 'بني ميلك', wilayaId: 42 },
  { name: 'بواسماعيل', wilayaId: 42 },
  { name: 'بورقيقة', wilayaId: 42 },
  { name: 'بوهارون', wilayaId: 42 },
  { name: 'تيبازة', wilayaId: 42 },
  { name: 'حجرة النص', wilayaId: 42 },
  { name: 'حجوط', wilayaId: 42 },
  { name: 'خميستي', wilayaId: 42 },
  { name: 'دواودة', wilayaId: 42 },
  { name: 'سيدي راشد', wilayaId: 42 },
  { name: 'سيدي سميان', wilayaId: 42 },
  { name: 'سيدي عمر', wilayaId: 42 },
  { name: 'سيدي غيلاس', wilayaId: 42 },
  { name: 'شرشال', wilayaId: 42 },
  { name: 'عين تاقورايت', wilayaId: 42 },
  { name: 'فوكة', wilayaId: 42 },
  { name: 'قوراية', wilayaId: 42 },
  { name: 'مراد', wilayaId: 42 },
  { name: 'مسلمون', wilayaId: 42 },
  { name: 'مناصر', wilayaId: 42 },
  { name: 'إبودرارن', wilayaId: 15 },
  { name: 'أبي يوسف', wilayaId: 15 },
  { name: 'أزفون', wilayaId: 15 },
  { name: 'أسي يوسف', wilayaId: 15 },
  { name: 'إعــكورن', wilayaId: 15 },
  { name: 'أغريب', wilayaId: 15 },
  { name: 'إفــرحــونن', wilayaId: 15 },
  { name: 'إفليـــسن', wilayaId: 15 },
  { name: 'أقرو', wilayaId: 15 },
  { name: 'أقني قغران', wilayaId: 15 },
  { name: 'إمســوحال', wilayaId: 15 },
  { name: 'أيت أومالو', wilayaId: 15 },
  { name: 'أيت بــوادو', wilayaId: 15 },
  { name: 'أيت بومهدي', wilayaId: 15 },
  { name: 'أيت تودرت', wilayaId: 15 },
  { name: 'أيت خليلي', wilayaId: 15 },
  { name: 'أيت شافع', wilayaId: 15 },
  { name: 'أيت عقـواشة', wilayaId: 15 },
  { name: 'أيت عيسى ميمون', wilayaId: 15 },
  { name: 'أيت محمود', wilayaId: 15 },
  { name: 'أيت يحيى', wilayaId: 15 },
  { name: 'آيت يحيى موسى', wilayaId: 15 },
  { name: 'إيجــار', wilayaId: 15 },
  { name: 'إيرجـــن', wilayaId: 15 },
  { name: 'إيفيغاء', wilayaId: 15 },
  { name: 'إيلولة أومـــالو', wilayaId: 15 },
  { name: 'إيلـيــلتـن', wilayaId: 15 },
  { name: 'اقبيل', wilayaId: 15 },
  { name: 'الأربعــاء ناث إيراثن', wilayaId: 15 },
  { name: 'بني دوالة', wilayaId: 15 },
  { name: 'بني زكــي', wilayaId: 15 },
  { name: 'بنــــي زمنزار', wilayaId: 15 },
  { name: 'بني عيسي', wilayaId: 15 },
  { name: 'بني يني', wilayaId: 15 },
  { name: 'بوجيمــــع', wilayaId: 15 },
  { name: 'بوزقــن', wilayaId: 15 },
  { name: 'بوغني', wilayaId: 15 },
  { name: 'بونوح', wilayaId: 15 },
  { name: 'تادمايت', wilayaId: 15 },
  { name: 'تيرمتين', wilayaId: 15 },
  { name: 'تيزي راشد', wilayaId: 15 },
  { name: 'تيزي غنيف', wilayaId: 15 },
  { name: 'تيزي نثلاثة', wilayaId: 15 },
  { name: 'تيزي وزو', wilayaId: 15 },
  { name: 'تيقـزيرت', wilayaId: 15 },
  { name: 'تيمـيزار', wilayaId: 15 },
  { name: 'ذراع الميزان', wilayaId: 15 },
  { name: 'ذراع بن خدة', wilayaId: 15 },
  { name: 'زكري', wilayaId: 15 },
  { name: 'سوق الاثنين', wilayaId: 15 },
  { name: 'سيدي نعمان', wilayaId: 15 },
  { name: 'صوامـــع', wilayaId: 15 },
  { name: 'عزازقة', wilayaId: 15 },
  { name: 'عين الحمام', wilayaId: 15 },
  { name: 'عين الزاوية', wilayaId: 15 },
  { name: 'فريحة', wilayaId: 15 },
  { name: 'فريقات', wilayaId: 15 },
  { name: 'ماكودة', wilayaId: 15 },
  { name: 'مشطراس', wilayaId: 15 },
  { name: 'معـــاتقة', wilayaId: 15 },
  { name: 'مقــلع', wilayaId: 15 },
  { name: 'مكيرة', wilayaId: 15 },
  { name: 'ميزرانـــة', wilayaId: 15 },
  { name: 'واسيف', wilayaId: 15 },
  { name: 'واضية', wilayaId: 15 },
  { name: 'واقنون', wilayaId: 15 },
  { name: 'يطــافن', wilayaId: 15 },
  { name: 'أولاد بسام', wilayaId: 38 },
  { name: 'الأربعاء', wilayaId: 38 },
  { name: 'الأزهرية', wilayaId: 38 },
  { name: 'العيون', wilayaId: 38 },
  { name: 'المعاصم', wilayaId: 38 },
  { name: 'الملعب', wilayaId: 38 },
  { name: 'اليوسفية', wilayaId: 38 },
  { name: 'برج الأمير عبد القادر', wilayaId: 38 },
  { name: 'برج بونعامة', wilayaId: 38 },
  { name: 'بني شعيب', wilayaId: 38 },
  { name: 'بني لحسن', wilayaId: 38 },
  { name: 'بوقائد', wilayaId: 38 },
  { name: 'تملاحت', wilayaId: 38 },
  { name: 'تيسمسيلت', wilayaId: 38 },
  { name: 'ثنية الاحد', wilayaId: 38 },
  { name: 'خميستي', wilayaId: 38 },
  { name: 'سيدي العنتري', wilayaId: 38 },
  { name: 'سيدي بوتوشنت', wilayaId: 38 },
  { name: 'سيدي سليمان', wilayaId: 38 },
  { name: 'سيدي عابد', wilayaId: 38 },
  { name: 'عماري', wilayaId: 38 },
  { name: 'لرجام', wilayaId: 38 },
  { name: 'أم العسل', wilayaId: 37 },
  { name: 'تندوف', wilayaId: 37 },
  { name: 'أراقن', wilayaId: 18 },
  { name: 'أولاد رابح', wilayaId: 18 },
  { name: 'أولاد يحيى خدروش', wilayaId: 18 },
  { name: 'الامير عبد القادر', wilayaId: 18 },
  { name: 'الجمعة بني حبيبي', wilayaId: 18 },
  { name: 'السطارة', wilayaId: 18 },
  { name: 'الشحنة', wilayaId: 18 },
  { name: 'الشقفة', wilayaId: 18 },
  { name: 'الطاهير', wilayaId: 18 },
  { name: 'العنصر', wilayaId: 18 },
  { name: 'العوانة', wilayaId: 18 },
  { name: 'القنار نشفي', wilayaId: 18 },
  { name: 'الميلية', wilayaId: 18 },
  { name: 'برج الطهر', wilayaId: 18 },
  { name: 'بودريعة بني ياجيس', wilayaId: 18 },
  { name: 'بوراوي بلهادف', wilayaId: 18 },
  { name: 'بوسيف أولاد عسكر', wilayaId: 18 },
  { name: 'تاكسنة', wilayaId: 18 },
  { name: 'جيجل', wilayaId: 18 },
  { name: 'جيملة', wilayaId: 18 },
  { name: 'خيري واد عجول', wilayaId: 18 },
  { name: 'زيامة منصورية', wilayaId: 18 },
  { name: 'سلمى بن زيادة', wilayaId: 18 },
  { name: 'سيدي عبد العزيز', wilayaId: 18 },
  { name: 'سيدي معروف', wilayaId: 18 },
  { name: 'غبالة', wilayaId: 18 },
  { name: 'قاوس', wilayaId: 18 },
  { name: 'وجانة', wilayaId: 18 },
  { name: 'أولاد رشاش', wilayaId: 40 },
  { name: 'الحامة', wilayaId: 40 },
  { name: 'الرميلة', wilayaId: 40 },
  { name: 'المحمل', wilayaId: 40 },
  { name: 'الولجة', wilayaId: 40 },
  { name: 'انسيغة', wilayaId: 40 },
  { name: 'بابار', wilayaId: 40 },
  { name: 'بغاي', wilayaId: 40 },
  { name: 'بوحمامة', wilayaId: 40 },
  { name: 'تاوزيانت', wilayaId: 40 },
  { name: 'جلال', wilayaId: 40 },
  { name: 'خنشلة', wilayaId: 40 },
  { name: 'خيران', wilayaId: 40 },
  { name: 'ششار', wilayaId: 40 },
  { name: 'شلية', wilayaId: 40 },
  { name: 'طامزة', wilayaId: 40 },
  { name: 'عين الطويلة', wilayaId: 40 },
  { name: 'قايس', wilayaId: 40 },
  { name: 'متوسة', wilayaId: 40 },
  { name: 'مصارة', wilayaId: 40 },
  { name: 'يابوس', wilayaId: 40 },
  { name: 'أوريسيا', wilayaId: 19 },
  { name: 'أولاد تبان', wilayaId: 19 },
  { name: 'أولاد سي أحمد', wilayaId: 19 },
  { name: 'أولاد صابر', wilayaId: 19 },
  { name: 'أولاد عدوان', wilayaId: 19 },
  { name: 'أيت نوال مزادة', wilayaId: 19 },
  { name: 'التلة', wilayaId: 19 },
  { name: 'الحامة', wilayaId: 19 },
  { name: 'الدهامشة', wilayaId: 19 },
  { name: 'الرصفة', wilayaId: 19 },
  { name: 'الطاية', wilayaId: 19 },
  { name: 'العلمة', wilayaId: 19 },
  { name: 'الولجة', wilayaId: 19 },
  { name: 'ايت تيزي', wilayaId: 19 },
  { name: 'بئر العرش', wilayaId: 19 },
  { name: 'بئر حدادة', wilayaId: 19 },
  { name: 'بابور', wilayaId: 19 },
  { name: 'بازر سكرة', wilayaId: 19 },
  { name: 'بلاعة', wilayaId: 19 },
  { name: 'بني شبانة', wilayaId: 19 },
  { name: 'بني عزيز', wilayaId: 19 },
  { name: 'بني فودة', wilayaId: 19 },
  { name: 'بني موحلي', wilayaId: 19 },
  { name: 'بني ورتيلان', wilayaId: 19 },
  { name: 'بني وسين', wilayaId: 19 },
  { name: 'بوسلام', wilayaId: 19 },
  { name: 'بوطالب', wilayaId: 19 },
  { name: 'بوعنداس', wilayaId: 19 },
  { name: 'بوقاعة', wilayaId: 19 },
  { name: 'بيضاء برج', wilayaId: 19 },
  { name: 'تاشودة', wilayaId: 19 },
  { name: 'تالة إيفاسن', wilayaId: 19 },
  { name: 'تيزي نبشار', wilayaId: 19 },
  { name: 'جميلة', wilayaId: 19 },
  { name: 'حربيل', wilayaId: 19 },
  { name: 'حمام السخنة', wilayaId: 19 },
  { name: 'حمام قرقور', wilayaId: 19 },
  { name: 'ذراع قبيلة', wilayaId: 19 },
  { name: 'سرج الغول', wilayaId: 19 },
  { name: 'سطيف', wilayaId: 19 },
  { name: 'صالح باي', wilayaId: 19 },
  { name: 'عموشة', wilayaId: 19 },
  { name: 'عين أرنات', wilayaId: 19 },
  { name: 'عين أزال', wilayaId: 19 },
  { name: 'عين الحجر', wilayaId: 19 },
  { name: 'عين الروى', wilayaId: 19 },
  { name: 'عين السبت', wilayaId: 19 },
  { name: 'عين الكبيرة', wilayaId: 19 },
  { name: 'عين عباسة', wilayaId: 19 },
  { name: 'عين لقراج', wilayaId: 19 },
  { name: 'عين ولمان', wilayaId: 19 },
  { name: 'قجال', wilayaId: 19 },
  { name: 'قصر الابطال', wilayaId: 19 },
  { name: 'قلال', wilayaId: 19 },
  { name: 'قلتة زرقاء', wilayaId: 19 },
  { name: 'قنزات', wilayaId: 19 },
  { name: 'ماوكلان', wilayaId: 19 },
  { name: 'مزلوق', wilayaId: 19 },
  { name: 'معاوية', wilayaId: 19 },
  { name: 'وادي البارد', wilayaId: 19 },
  { name: 'أولاد إبراهيم', wilayaId: 20 },
  { name: 'أولاد خالد', wilayaId: 20 },
  { name: 'الحساسنة', wilayaId: 20 },
  { name: 'المعمورة', wilayaId: 20 },
  { name: 'تيرسين', wilayaId: 20 },
  { name: 'دوي ثابت', wilayaId: 20 },
  { name: 'سعيدة', wilayaId: 20 },
  { name: 'سيدي احمد', wilayaId: 20 },
  { name: 'سيدي بوبكر', wilayaId: 20 },
  { name: 'سيدي عمر', wilayaId: 20 },
  { name: 'عين الحجر', wilayaId: 20 },
  { name: 'عين السخونة', wilayaId: 20 },
  { name: 'عين السلطان', wilayaId: 20 },
  { name: 'مولاي العربي', wilayaId: 20 },
  { name: 'هونت', wilayaId: 20 },
  { name: 'يوب', wilayaId: 20 },
  { name: 'أم الطوب', wilayaId: 21 },
  { name: 'أولاد حبابة', wilayaId: 21 },
  { name: 'أولاد عطية', wilayaId: 21 },
  { name: 'الحدائق', wilayaId: 21 },
  { name: 'الحروش', wilayaId: 21 },
  { name: 'الزيتونة', wilayaId: 21 },
  { name: 'السبت', wilayaId: 21 },
  { name: 'الشرايع', wilayaId: 21 },
  { name: 'الغدير', wilayaId: 21 },
  { name: 'القل', wilayaId: 21 },
  { name: 'الكركرة', wilayaId: 21 },
  { name: 'المرسى', wilayaId: 21 },
  { name: 'الولجة بولبلوط', wilayaId: 21 },
  { name: 'بكوش لخضر', wilayaId: 21 },
  { name: 'بن عزوز', wilayaId: 21 },
  { name: 'بني بشير', wilayaId: 21 },
  { name: 'بني زيد', wilayaId: 21 },
  { name: 'بني ولبان', wilayaId: 21 },
  { name: 'بوشطاطة', wilayaId: 21 },
  { name: 'بين الويدان', wilayaId: 21 },
  { name: 'تمالوس', wilayaId: 21 },
  { name: 'جندل سعدي محمد', wilayaId: 21 },
  { name: 'حمادي كرومة', wilayaId: 21 },
  { name: 'خناق مايو', wilayaId: 21 },
  { name: 'رمضان جمال', wilayaId: 21 },
  { name: 'زردازة', wilayaId: 21 },
  { name: 'سكيكدة', wilayaId: 21 },
  { name: 'سيدي مزغيش', wilayaId: 21 },
  { name: 'صالح بو الشعور', wilayaId: 21 },
  { name: 'عزابة', wilayaId: 21 },
  { name: 'عين بوزيان', wilayaId: 21 },
  { name: 'عين زويت', wilayaId: 21 },
  { name: 'عين شرشار', wilayaId: 21 },
  { name: 'عين قشرة', wilayaId: 21 },
  { name: 'فلفلة', wilayaId: 21 },
  { name: 'قنواع', wilayaId: 21 },
  { name: 'مجاز الدشيش', wilayaId: 21 },
  { name: 'وادي الزهور', wilayaId: 21 },
  { name: 'أم العظايم', wilayaId: 41 },
  { name: 'أولاد إدريس', wilayaId: 41 },
  { name: 'أولاد مومن', wilayaId: 41 },
  { name: 'الحدادة', wilayaId: 41 },
  { name: 'الحنانشة', wilayaId: 41 },
  { name: 'الدريعة', wilayaId: 41 },
  { name: 'الرقوبة', wilayaId: 41 },
  { name: 'الزعرورية', wilayaId: 41 },
  { name: 'الزوابي', wilayaId: 41 },
  { name: 'المراهنة', wilayaId: 41 },
  { name: 'بئر بوحوش', wilayaId: 41 },
  { name: 'تاورة', wilayaId: 41 },
  { name: 'ترقالت', wilayaId: 41 },
  { name: 'تيفاش', wilayaId: 41 },
  { name: 'خميسة', wilayaId: 41 },
  { name: 'سافل الويدان', wilayaId: 41 },
  { name: 'سدراتة', wilayaId: 41 },
  { name: 'سوق أهراس', wilayaId: 41 },
  { name: 'سيدي فرج', wilayaId: 41 },
  { name: 'عين الزانة', wilayaId: 41 },
  { name: 'عين سلطان', wilayaId: 41 },
  { name: 'لخضارة', wilayaId: 41 },
  { name: 'مداوروش', wilayaId: 41 },
  { name: 'مشروحة', wilayaId: 41 },
  { name: 'وادي الكبريت', wilayaId: 41 },
  { name: 'ويلان', wilayaId: 41 },
  { name: 'الحصيبة', wilayaId: 22 },
  { name: 'السهالة الثورة', wilayaId: 22 },
  { name: 'الضاية', wilayaId: 22 },
  { name: 'العمارنة', wilayaId: 22 },
  { name: 'بئر الحمام', wilayaId: 22 },
  { name: 'بضرابين المقراني', wilayaId: 22 },
  { name: 'بلعربي', wilayaId: 22 },
  { name: 'بن باديس', wilayaId: 22 },
  { name: 'بن عشيبة شلية', wilayaId: 22 },
  { name: 'بوجبهة البرج', wilayaId: 22 },
  { name: 'بوخنفيس', wilayaId: 22 },
  { name: 'تاودموت', wilayaId: 22 },
  { name: 'تسالة', wilayaId: 22 },
  { name: 'تغاليمت', wilayaId: 22 },
  { name: 'تفسور', wilayaId: 22 },
  { name: 'تلاغ', wilayaId: 22 },
  { name: 'تلموني', wilayaId: 22 },
  { name: 'تنيرة', wilayaId: 22 },
  { name: 'حاسي دحو', wilayaId: 22 },
  { name: 'حاسي زهانة', wilayaId: 22 },
  { name: 'راس الماء', wilayaId: 22 },
  { name: 'رجم دموش', wilayaId: 22 },
  { name: 'زروالة', wilayaId: 22 },
  { name: 'سفيزف', wilayaId: 22 },
  { name: 'سيدي ابراهيم', wilayaId: 22 },
  { name: 'سيدي بلعباس', wilayaId: 22 },
  { name: 'سيدي حمادوش', wilayaId: 22 },
  { name: 'سيدي خالد', wilayaId: 22 },
  { name: 'سيدي دحو الزاير', wilayaId: 22 },
  { name: 'سيدي شعيب', wilayaId: 22 },
  { name: 'سيدي علي بن يوب', wilayaId: 22 },
  { name: 'سيدي علي بوسيدي', wilayaId: 22 },
  { name: 'سيدي لحسن', wilayaId: 22 },
  { name: 'سيدي يعقوب', wilayaId: 22 },
  { name: 'شيطوان البلايلة', wilayaId: 22 },
  { name: 'طابية', wilayaId: 22 },
  { name: 'عين أدن', wilayaId: 22 },
  { name: 'عين البرد', wilayaId: 22 },
  { name: 'عين الثريد', wilayaId: 22 },
  { name: 'عين تندمين', wilayaId: 22 },
  { name: 'عين قادة', wilayaId: 22 },
  { name: 'لمطار', wilayaId: 22 },
  { name: 'مرحوم', wilayaId: 22 },
  { name: 'مرين', wilayaId: 22 },
  { name: 'مزاورو', wilayaId: 22 },
  { name: 'مسيد', wilayaId: 22 },
  { name: 'مصطفى بن ابراهيم', wilayaId: 22 },
  { name: 'مكدرة', wilayaId: 22 },
  { name: 'مولاي سليسن', wilayaId: 22 },
  { name: 'وادي السبع', wilayaId: 22 },
  { name: 'وادي تاوريرة', wilayaId: 22 },
  { name: 'وادي سفيون', wilayaId: 22 },
  { name: 'البوني', wilayaId: 23 },
  { name: 'التريعات', wilayaId: 23 },
  { name: 'الحجار', wilayaId: 23 },
  { name: 'الشرفة', wilayaId: 23 },
  { name: 'العلمة', wilayaId: 23 },
  { name: 'برحال', wilayaId: 23 },
  { name: 'سيدي عمار', wilayaId: 23 },
  { name: 'شطايبي', wilayaId: 23 },
  { name: 'عنابة', wilayaId: 23 },
  { name: 'عين الباردة', wilayaId: 23 },
  { name: 'واد العنب', wilayaId: 23 },
  { name: 'إبن علال', wilayaId: 44 },
  { name: 'الحسانية', wilayaId: 44 },
  { name: 'الحسينية', wilayaId: 44 },
  { name: 'العامرة', wilayaId: 44 },
  { name: 'العبادية', wilayaId: 44 },
  { name: 'العطاف', wilayaId: 44 },
  { name: 'الماين', wilayaId: 44 },
  { name: 'المخاطرية', wilayaId: 44 },
  { name: 'بئر ولد خليفة', wilayaId: 44 },
  { name: 'بالعاص', wilayaId: 44 },
  { name: 'بربوش', wilayaId: 44 },
  { name: 'برج الأمير خالد', wilayaId: 44 },
  { name: 'بطحية', wilayaId: 44 },
  { name: 'بوراشد', wilayaId: 44 },
  { name: 'بومدفع', wilayaId: 44 },
  { name: 'تاشتة زقاغة', wilayaId: 44 },
  { name: 'تبركانين', wilayaId: 44 },
  { name: 'جليدة', wilayaId: 44 },
  { name: 'جمعة أولاد الشيخ', wilayaId: 44 },
  { name: 'جندل', wilayaId: 44 },
  { name: 'حمام ريغة', wilayaId: 44 },
  { name: 'خميس مليانة', wilayaId: 44 },
  { name: 'روينة', wilayaId: 44 },
  { name: 'زدين', wilayaId: 44 },
  { name: 'سيدي الأخضر', wilayaId: 44 },
  { name: 'طارق بن زياد', wilayaId: 44 },
  { name: 'عريب', wilayaId: 44 },
  { name: 'عين الاشياخ', wilayaId: 44 },
  { name: 'عين البنيان', wilayaId: 44 },
  { name: 'عين التركي', wilayaId: 44 },
  { name: 'عين الدفلى', wilayaId: 44 },
  { name: 'عين السلطان', wilayaId: 44 },
  { name: 'عين بويحيى', wilayaId: 44 },
  { name: 'مليانة', wilayaId: 44 },
  { name: 'وادي الشرفاء', wilayaId: 44 },
  { name: 'وادي جمعة', wilayaId: 44 },
  { name: 'أغلال', wilayaId: 46 },
  { name: 'أولاد الكيحل', wilayaId: 46 },
  { name: 'أولاد بوجمعة', wilayaId: 46 },
  { name: 'الأمير عبد القادر', wilayaId: 46 },
  { name: 'الحساسنة', wilayaId: 46 },
  { name: 'العامرية', wilayaId: 46 },
  { name: 'المالح', wilayaId: 46 },
  { name: 'المساعيد', wilayaId: 46 },
  { name: 'بني صاف', wilayaId: 46 },
  { name: 'بوزجار', wilayaId: 46 },
  { name: 'تارقة', wilayaId: 46 },
  { name: 'تامزورة', wilayaId: 46 },
  { name: 'حاسي الغلة', wilayaId: 46 },
  { name: 'حمام بوحجر', wilayaId: 46 },
  { name: 'سيدي أورياش', wilayaId: 46 },
  { name: 'سيدي الصافي', wilayaId: 46 },
  { name: 'سيدي بن عدة', wilayaId: 46 },
  { name: 'سيدي بومدين', wilayaId: 46 },
  { name: 'شعبة اللحم', wilayaId: 46 },
  { name: 'شنتوف', wilayaId: 46 },
  { name: 'عقب الليل', wilayaId: 46 },
  { name: 'عين الأربعاء', wilayaId: 46 },
  { name: 'عين الطلبة', wilayaId: 46 },
  { name: 'عين الكيحل', wilayaId: 46 },
  { name: 'عين تيموشنت', wilayaId: 46 },
  { name: 'وادي الصباح', wilayaId: 46 },
  { name: 'وادي برقش', wilayaId: 46 },
  { name: 'ولهاصة الغرابة', wilayaId: 46 },
  { name: 'العطف', wilayaId: 47 },
  { name: 'القرارة', wilayaId: 47 },
  { name: 'المنصورة', wilayaId: 47 },
  { name: 'المنيعة', wilayaId: 47 },
  { name: 'بريان', wilayaId: 47 },
  { name: 'بونورة', wilayaId: 47 },
  { name: 'حاسي الفحل', wilayaId: 47 },
  { name: 'حاسي القارة', wilayaId: 47 },
  { name: 'زلفانة', wilayaId: 47 },
  { name: 'سبسب', wilayaId: 47 },
  { name: 'ضاية بن ضحوة', wilayaId: 47 },
  { name: 'غرداية', wilayaId: 47 },
  { name: 'متليلي', wilayaId: 47 },
  { name: 'أولاد سيدي الميهوب', wilayaId: 48 },
  { name: 'أولاد يعيش', wilayaId: 48 },
  { name: 'الحاسي', wilayaId: 48 },
  { name: 'الحمادنة', wilayaId: 48 },
  { name: 'الرمكة', wilayaId: 48 },
  { name: 'القطار', wilayaId: 48 },
  { name: 'القلعة', wilayaId: 48 },
  { name: 'المطمر', wilayaId: 48 },
  { name: 'الولجة', wilayaId: 48 },
  { name: 'بلعسل بوزقزة', wilayaId: 48 },
  { name: 'بن داود', wilayaId: 48 },
  { name: 'بني درقن', wilayaId: 48 },
  { name: 'بني زنطيس', wilayaId: 48 },
  { name: 'جديوية', wilayaId: 48 },
  { name: 'حد الشكالة', wilayaId: 48 },
  { name: 'حمري', wilayaId: 48 },
  { name: 'دار بن عبد الله', wilayaId: 48 },
  { name: 'زمورة', wilayaId: 48 },
  { name: 'سوق الحد', wilayaId: 48 },
  { name: 'سيدي خطاب', wilayaId: 48 },
  { name: 'سيدي أمحمد بن علي', wilayaId: 48 },
  { name: 'سيدي امحمد بن عودة', wilayaId: 48 },
  { name: 'سيدي سعادة', wilayaId: 48 },
  { name: 'سيدي لزرق', wilayaId: 48 },
  { name: 'عمي موسى', wilayaId: 48 },
  { name: 'عين الرحمة', wilayaId: 48 },
  { name: 'عين طارق', wilayaId: 48 },
  { name: 'غليزان', wilayaId: 48 },
  { name: 'لحلاف', wilayaId: 48 },
  { name: 'مازونة', wilayaId: 48 },
  { name: 'مديونة', wilayaId: 48 },
  { name: 'مرجة سيدي عابد', wilayaId: 48 },
  { name: 'منداس', wilayaId: 48 },
  { name: 'وادي الجمعة', wilayaId: 48 },
  { name: 'وادي السلام', wilayaId: 48 },
  { name: 'وادي رهيو', wilayaId: 48 },
  { name: 'واريزان', wilayaId: 48 },
  { name: 'يلل', wilayaId: 48 },
  { name: 'الدهوارة', wilayaId: 24 },
  { name: 'الركنية', wilayaId: 24 },
  { name: 'الفجوج', wilayaId: 24 },
  { name: 'برج صباط', wilayaId: 24 },
  { name: 'بلخير', wilayaId: 24 },
  { name: 'بن جراح', wilayaId: 24 },
  { name: 'بني مزلين', wilayaId: 24 },
  { name: 'بوحشانة', wilayaId: 24 },
  { name: 'بوحمدان', wilayaId: 24 },
  { name: 'بوشقوف', wilayaId: 24 },
  { name: 'بوعاتي محمود', wilayaId: 24 },
  { name: 'بومهرة أحمد', wilayaId: 24 },
  { name: 'تاملوكة', wilayaId: 24 },
  { name: 'جبالة الخميسي', wilayaId: 24 },
  { name: 'حمام النبايل', wilayaId: 24 },
  { name: 'حمام دباغ', wilayaId: 24 },
  { name: 'رأس العقبة', wilayaId: 24 },
  { name: 'سلاوة عنونة', wilayaId: 24 },
  { name: 'عين العربي', wilayaId: 24 },
  { name: 'عين بن بيضاء', wilayaId: 24 },
  { name: 'عين رقادة', wilayaId: 24 },
  { name: 'عين صندل', wilayaId: 24 },
  { name: 'عين مخلوف', wilayaId: 24 },
  { name: 'قالمة', wilayaId: 24 },
  { name: 'قلعة بوصبع', wilayaId: 24 },
  { name: 'لخزارة', wilayaId: 24 },
  { name: 'مجاز الصفاء', wilayaId: 24 },
  { name: 'مجاز عمار', wilayaId: 24 },
  { name: 'نشماية', wilayaId: 24 },
  { name: 'هواري بومدين', wilayaId: 24 },
  { name: 'هيليوبوليس', wilayaId: 24 },
  { name: 'وادي الزناتي', wilayaId: 24 },
  { name: 'وادي الشحم', wilayaId: 24 },
  { name: 'وادي فراغة', wilayaId: 24 },
  { name: 'أبن باديس الهرية', wilayaId: 25 },
  { name: 'أولاد رحمون', wilayaId: 25 },
  { name: 'ابن زياد', wilayaId: 25 },
  { name: 'الخروب', wilayaId: 25 },
  { name: 'بني حميدان', wilayaId: 25 },
  { name: 'بوجريو مسعود', wilayaId: 25 },
  { name: 'حامة بوزيان', wilayaId: 25 },
  { name: 'ديدوش مراد', wilayaId: 25 },
  { name: 'زيغود يوسف', wilayaId: 25 },
  { name: 'علي منجلي', wilayaId: 25 },
  { name: 'عين السمارة', wilayaId: 25 },
  { name: 'عين عبيد', wilayaId: 25 },
  { name: 'أولاد بوغالم', wilayaId: 27 },
  { name: 'أولاد مع الله', wilayaId: 27 },
  { name: 'الحسيان', wilayaId: 27 },
  { name: 'السوافلية', wilayaId: 27 },
  { name: 'الطواهرية', wilayaId: 27 },
  { name: 'بن عبد المالك رمضان', wilayaId: 27 },
  { name: 'بوقيراط', wilayaId: 27 },
  { name: 'تزقايت', wilayaId: 27 },
  { name: 'حاسي ماماش', wilayaId: 27 },
  { name: 'حجاج', wilayaId: 27 },
  { name: 'خضرة', wilayaId: 27 },
  { name: 'خير الدين', wilayaId: 27 },
  { name: 'ستيدية', wilayaId: 27 },
  { name: 'سور', wilayaId: 27 },
  { name: 'سيدي بلعطار', wilayaId: 27 },
  { name: 'سيدي علي', wilayaId: 27 },
  { name: 'سيدي لخضر', wilayaId: 27 },
  { name: 'سيرات', wilayaId: 27 },
  { name: 'صفصاف', wilayaId: 27 },
  { name: 'صيادة', wilayaId: 27 },
  { name: 'عشعاشة', wilayaId: 27 },
  { name: 'عين بودينار', wilayaId: 27 },
  { name: 'عين تادلس', wilayaId: 27 },
  { name: 'عين سيدي الشريف', wilayaId: 27 },
  { name: 'عين نويسي', wilayaId: 27 },
  { name: 'فرناقة', wilayaId: 27 },
  { name: 'ماسرة', wilayaId: 27 },
  { name: 'مزغران', wilayaId: 27 },
  { name: 'مستغانم', wilayaId: 27 },
  { name: 'منصورة', wilayaId: 27 },
  { name: 'نكمارية', wilayaId: 27 },
  { name: 'وادي الخير', wilayaId: 27 },
  { name: 'البرج', wilayaId: 29 },
  { name: 'الحشم', wilayaId: 29 },
  { name: 'السهايلية', wilayaId: 29 },
  { name: 'الشرفاء', wilayaId: 29 },
  { name: 'العلايمية', wilayaId: 29 },
  { name: 'الغمري', wilayaId: 29 },
  { name: 'القرط', wilayaId: 29 },
  { name: 'القطنة', wilayaId: 29 },
  { name: 'القعدة', wilayaId: 29 },
  { name: 'المأمونية', wilayaId: 29 },
  { name: 'المحمدية', wilayaId: 29 },
  { name: 'المطمور', wilayaId: 29 },
  { name: 'المنور', wilayaId: 29 },
  { name: 'بنيان', wilayaId: 29 },
  { name: 'بوحنيفية', wilayaId: 29 },
  { name: 'بوهني', wilayaId: 29 },
  { name: 'تيزي', wilayaId: 29 },
  { name: 'تيغنيف', wilayaId: 29 },
  { name: 'حسين', wilayaId: 29 },
  { name: 'خلوية', wilayaId: 29 },
  { name: 'رأس عين عميروش', wilayaId: 29 },
  { name: 'زلامطة', wilayaId: 29 },
  { name: 'زهانة', wilayaId: 29 },
  { name: 'سجرارة', wilayaId: 29 },
  { name: 'سيدي بوسعيد', wilayaId: 29 },
  { name: 'سيدي عبد الجبار', wilayaId: 29 },
  { name: 'سيدي عبد المومن', wilayaId: 29 },
  { name: 'سيدي قادة', wilayaId: 29 },
  { name: 'سيق', wilayaId: 29 },
  { name: 'عقاز', wilayaId: 29 },
  { name: 'عوف', wilayaId: 29 },
  { name: 'عين أفرص', wilayaId: 29 },
  { name: 'عين فارس', wilayaId: 29 },
  { name: 'عين فراح', wilayaId: 29 },
  { name: 'عين فكان', wilayaId: 29 },
  { name: 'غروس', wilayaId: 29 },
  { name: 'غريس', wilayaId: 29 },
  { name: 'فراقيق', wilayaId: 29 },
  { name: 'فروحة', wilayaId: 29 },
  { name: 'قرجوم', wilayaId: 29 },
  { name: 'ماقضة', wilayaId: 29 },
  { name: 'ماوسة', wilayaId: 29 },
  { name: 'معسكر', wilayaId: 29 },
  { name: 'مقطع الدوز', wilayaId: 29 },
  { name: 'نسمط', wilayaId: 29 },
  { name: 'وادي الأبطال', wilayaId: 29 },
  { name: 'وادي التاغية', wilayaId: 29 },
  { name: 'عين البيضاء أحريش', wilayaId: 43 },
  { name: 'أبن يحيى عبد الرحمن', wilayaId: 43 },
  { name: 'أحمد راشدي', wilayaId: 43 },
  { name: 'أولاد خلوف', wilayaId: 43 },
  { name: 'اعميرة اراس', wilayaId: 43 },
  { name: 'التلاغمة', wilayaId: 43 },
  { name: 'الرواشد', wilayaId: 43 },
  { name: 'الشيقارة', wilayaId: 43 },
  { name: 'العياضي برباس', wilayaId: 43 },
  { name: 'بوحاتم', wilayaId: 43 },
  { name: 'تاجنانت', wilayaId: 43 },
  { name: 'ترعي باينان', wilayaId: 43 },
  { name: 'تسالة لمطاعي', wilayaId: 43 },
  { name: 'تسدان حدادة', wilayaId: 43 },
  { name: 'تيبرقنت', wilayaId: 43 },
  { name: 'حمالة', wilayaId: 43 },
  { name: 'دراحي بوصلاح', wilayaId: 43 },
  { name: 'زغاية', wilayaId: 43 },
  { name: 'سيدي خليفة', wilayaId: 43 },
  { name: 'سيدي مروان', wilayaId: 43 },
  { name: 'شلغوم العيد', wilayaId: 43 },
  { name: 'عين التين', wilayaId: 43 },
  { name: 'عين ملوك', wilayaId: 43 },
  { name: 'فرجيوة', wilayaId: 43 },
  { name: 'قرارم قوقة', wilayaId: 43 },
  { name: 'مشيرة', wilayaId: 43 },
  { name: 'ميلة', wilayaId: 43 },
  { name: 'مينار زارزة', wilayaId: 43 },
  { name: 'وادي العثمانية', wilayaId: 43 },
  { name: 'وادي النجاء', wilayaId: 43 },
  { name: 'وادي سقان', wilayaId: 43 },
  { name: 'يحيى بني قشة', wilayaId: 43 },
  { name: 'البرمة', wilayaId: 30 },
  { name: 'الحجيرة', wilayaId: 30 },
  { name: 'الزاوية العابدية', wilayaId: 30 },
  { name: 'الطيبات', wilayaId: 30 },
  { name: 'العالية', wilayaId: 30 },
  { name: 'المقارين', wilayaId: 30 },
  { name: 'المنقر', wilayaId: 30 },
  { name: 'النزلة', wilayaId: 30 },
  { name: 'انقوسة', wilayaId: 30 },
  { name: 'بلدة اعمر', wilayaId: 30 },
  { name: 'بن ناصر', wilayaId: 30 },
  { name: 'تبسبست', wilayaId: 30 },
  { name: 'تقرت', wilayaId: 30 },
  { name: 'تماسين', wilayaId: 30 },
  { name: 'حاسي بن عبد الله', wilayaId: 30 },
  { name: 'حاسي مسعود', wilayaId: 30 },
  { name: 'سيدي خويلد', wilayaId: 30 },
  { name: 'سيدي سليمان', wilayaId: 30 },
  { name: 'عين البيضاء', wilayaId: 30 },
  { name: 'ورقلة', wilayaId: 30 },
  { name: 'أرزيو', wilayaId: 31 },
  { name: 'السانية', wilayaId: 31 },
  { name: 'بئر الجير', wilayaId: 31 },
  { name: 'بطيوة', wilayaId: 31 },
  { name: 'بوتليليس', wilayaId: 31 },
  { name: 'عين الترك', wilayaId: 31 },
  { name: 'قديل', wilayaId: 31 },
  { name: 'وادي تليلات', wilayaId: 31 },
  { name: 'البراية', wilayaId: 31 },
  { name: 'العنصر', wilayaId: 31 },
  { name: 'الكرمة', wilayaId: 31 },
  { name: 'المرسى الكبير', wilayaId: 31 },
  { name: 'بن فريحة', wilayaId: 31 },
  { name: 'بوصفر', wilayaId: 31 },
  { name: 'بوفتيس', wilayaId: 31 },
  { name: 'حاسي بن عقبة', wilayaId: 31 },
  { name: 'حاسي بونيف', wilayaId: 31 },
  { name: 'حاسي مفسوخ', wilayaId: 31 },
  { name: 'سيدي الشحمي', wilayaId: 31 },
  { name: 'سيدي بن يبقى', wilayaId: 31 },
  { name: 'طفراوي', wilayaId: 31 },
  { name: 'عين البية', wilayaId: 31 },
  { name: 'عين الكرمة', wilayaId: 31 },
  { name: 'مرسى الحجاج', wilayaId: 31 },
  { name: 'مسرغين', wilayaId: 31 },
  // Wilayas 49-58 (noms français - dataset 48 wilayas uniquement)
  { name: 'Aougrout', wilayaId: 49 },
  { name: 'Charouine', wilayaId: 49 },
  { name: 'Deldoul', wilayaId: 49 },
  { name: 'Ksar Kaddour', wilayaId: 49 },
  { name: 'Metarfa', wilayaId: 49 },
  { name: 'Ouled Aissa', wilayaId: 49 },
  { name: 'Ouled Said', wilayaId: 49 },
  { name: 'Talmine', wilayaId: 49 },
  { name: 'Timimoun', wilayaId: 49 },
  { name: 'Tinerkouk', wilayaId: 49 },
  { name: 'Bordj Badji Mokhtar', wilayaId: 50 },
  { name: 'Timiaouine', wilayaId: 50 },
  { name: 'Besbes', wilayaId: 51 },
  { name: 'Ech Chaiba', wilayaId: 51 },
  { name: 'Doucen', wilayaId: 51 },
  { name: 'Ouled Djellal', wilayaId: 51 },
  { name: 'Sidi Khaled', wilayaId: 51 },
  { name: 'Ras El Miaad', wilayaId: 51 },
  { name: 'Beni Abbes', wilayaId: 52 },
  { name: 'Ouled Khodeir', wilayaId: 52 },
  { name: 'Timoudi', wilayaId: 52 },
  { name: 'Beni Ikhlef', wilayaId: 52 },
  { name: 'Igli', wilayaId: 52 },
  { name: 'Tabelbala', wilayaId: 52 },
  { name: 'El Ouata', wilayaId: 52 },
  { name: 'Kerzaz', wilayaId: 52 },
  { name: 'Ksabi', wilayaId: 52 },
  { name: 'Tamtert', wilayaId: 52 },
  { name: 'In Salah', wilayaId: 53 },
  { name: 'Foggaret Ezzaouia', wilayaId: 53 },
  { name: 'In Ghar', wilayaId: 53 },
  { name: 'In Guezzam', wilayaId: 54 },
  { name: 'Tin Zaouatine', wilayaId: 54 },
  { name: 'Benaceur', wilayaId: 55 },
  { name: 'Blidet Amor', wilayaId: 55 },
  { name: 'El Allia', wilayaId: 55 },
  { name: 'El Hadjira', wilayaId: 55 },
  { name: 'Megarine', wilayaId: 55 },
  { name: "M'Naguer", wilayaId: 55 },
  { name: 'Nezla', wilayaId: 55 },
  { name: 'Sidi Slimane', wilayaId: 55 },
  { name: 'Taibet', wilayaId: 55 },
  { name: 'Temacine', wilayaId: 55 },
  { name: 'Tebesbest', wilayaId: 55 },
  { name: 'Touggourt', wilayaId: 55 },
  { name: 'Zaouia El Abidia', wilayaId: 55 },
  { name: 'Djanet', wilayaId: 56 },
  { name: 'Bordj El Haouas', wilayaId: 56 },
  { name: 'Djamaa', wilayaId: 57 },
  { name: "El M'Ghair", wilayaId: 57 },
  { name: 'Merara', wilayaId: 57 },
  { name: 'Oum Touyour', wilayaId: 57 },
  { name: 'Sidi Amrane', wilayaId: 57 },
  { name: 'Sidi Khellil', wilayaId: 57 },
  { name: 'Still', wilayaId: 57 },
  { name: 'Tendla', wilayaId: 57 },
  { name: 'El Menia', wilayaId: 58 },
  { name: 'Hassi Gara', wilayaId: 58 },
  { name: 'Hassi Fehal', wilayaId: 58 },
];

const PRODUCTS = [
  {
    name: 'Smartphone Galaxy S24', price: 249900, oldPrice: 289900,
    color: "#000000", sku: 'SAM-S24-256',
    images: ['https://placehold.co/400x400/cb11ab/white?text=S24', 'https://placehold.co/400x400/481173/white?text=S24+2', 'https://placehold.co/400x400/222/white?text=S24+3', 'https://placehold.co/400x400/cb11ab/white?text=S24+4', 'https://placehold.co/400x400/333/white?text=S24+5'],
    description: 'Smartphone Samsung 256Go, écran 6.8", appareil 200MP - Livraison rapide'
  },
  {
    name: 'iPhone 16 Pro Max', price: 289900, oldPrice: 329900,
    color: "#1a365d", sku: 'APP-IP16PM-256',
    images: ['https://placehold.co/400x400/481173/white?text=iPhone16', 'https://placehold.co/400x400/cb11ab/white?text=iPhone+2', 'https://placehold.co/400x400/222/white?text=iPhone+3', 'https://placehold.co/400x400/481173/white?text=iPhone+4', 'https://placehold.co/400x400/333/white?text=iPhone+5'],
    description: 'Apple iPhone 16 Pro Max 256Go, titane, caméra 48MP'
  },
  {
    name: 'AirPods Pro 2', price: 49900, oldPrice: 59900,
    color: "#7c3aed", sku: 'APP-AIRP2-USB',
    images: ['https://placehold.co/400x400/cb11ab/white?text=AirPods', 'https://placehold.co/400x400/481173/white?text=AirPods+2', 'https://placehold.co/400x400/222/white?text=AirPods+3', 'https://placehold.co/400x400/cb11ab/white?text=AirPods+4', 'https://placehold.co/400x400/333/white?text=AirPods+5'],
    description: 'AirPods Pro 2 USB-C, réduction de bruit active'
  },
  {
    name: 'Chaussures Nike Air Max', price: 49900, oldPrice: 59900,
    color: "#dc2626", sku: 'NIK-AIRMX-270',
    images: ['https://placehold.co/400x400/481173/white?text=Nike', 'https://placehold.co/400x400/cb11ab/white?text=Nike+2', 'https://placehold.co/400x400/222/white?text=Nike+3', 'https://placehold.co/400x400/333/white?text=Nike+4', 'https://placehold.co/400x400/481173/white?text=Nike+5'],
    description: 'Nike Air Max 270, confort et style'
  },
  {
    name: 'Parfum Chanel N°5', price: 54900, oldPrice: 64900,
    color: "#059669", sku: 'CHAN-N5-50ML',
    images: ['https://placehold.co/400x400/cb11ab/white?text=Chanel5', 'https://placehold.co/400x400/481173/white?text=Chanel+2', 'https://placehold.co/400x400/222/white?text=Chanel+3', 'https://placehold.co/400x400/333/white?text=Chanel+4', 'https://placehold.co/400x400/cb11ab/white?text=Chanel+5'],
    description: 'Parfum Chanel N°5, 50ml, élégance française'
  },
  {
    name: 'Casque Sony WH-1000XM5', price: 99900, oldPrice: 119900,
    color: "#2563eb", sku: 'SON-WHXM5-BLK',
    images: ['https://placehold.co/400x400/481173/white?text=SonyXM5', 'https://placehold.co/400x400/cb11ab/white?text=Sony+2', 'https://placehold.co/400x400/222/white?text=Sony+3', 'https://placehold.co/400x400/cb11ab/white?text=Sony+4', 'https://placehold.co/400x400/333/white?text=Sony+5'],
    description: 'Casque sans fil Sony, réduction de bruit adaptative'
  },
  {
    name: 'Sac à main Dior', price: 149900, oldPrice: null,
    color: "#d97706", sku: 'DIOR-BAG-LTR',
    images: ['https://placehold.co/400x400/cb11ab/white?text=Dior', 'https://placehold.co/400x400/481173/white?text=Dior+2', 'https://placehold.co/400x400/222/white?text=Dior+3', 'https://placehold.co/400x400/333/white?text=Dior+4', 'https://placehold.co/400x400/cb11ab/white?text=Dior+5'],
    description: 'Sac à main Dior femme, cuir de qualité'
  },
  {
    name: 'Montre connectée Galaxy Watch', price: 89900, oldPrice: 109900,
    color: "#be185d", sku: 'SAM-GW6C-44',
    images: ['https://placehold.co/400x400/481173/white?text=Watch6', 'https://placehold.co/400x400/cb11ab/white?text=Watch+2', 'https://placehold.co/400x400/222/white?text=Watch+3', 'https://placehold.co/400x400/333/white?text=Watch+4', 'https://placehold.co/400x400/481173/white?text=Watch+5'],
    description: 'Samsung Galaxy Watch 6 Classic, santé et fitness'
  },
  {
    name: 'T-shirt Nike Sportswear', price: 5900, oldPrice: 7900,
    color: "#000000", sku: 'NIK-TS-BLK',
    images: ['https://placehold.co/400x400/cb11ab/white?text=TSHIRT', 'https://placehold.co/400x400/481173/white?text=TSHIRT+2', 'https://placehold.co/400x400/222/white?text=TSHIRT+3', 'https://placehold.co/400x400/cb11ab/white?text=TSHIRT+4', 'https://placehold.co/400x400/333/white?text=TSHIRT+5'],
    description: 'T-shirt Nike Dri-FIT, confort et style sportif'
  },
  {
    name: 'Enceinte JBL Flip 6', price: 29900, oldPrice: null,
    color: "#4f46e5", sku: 'JBL-FLP6-BLU',
    images: ['https://placehold.co/400x400/481173/white?text=JBL', 'https://placehold.co/400x400/cb11ab/white?text=JBL+2', 'https://placehold.co/400x400/222/white?text=JBL+3', 'https://placehold.co/400x400/333/white?text=JBL+4', 'https://placehold.co/400x400/481173/white?text=JBL+5'],
    description: 'Enceinte Bluetooth portable JBL Flip 6, son puissant'
  },
];

async function main() {
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.product.deleteMany();
  await prisma.commune.deleteMany();
  await prisma.wilaya.deleteMany();

  await prisma.wilaya.createMany({ data: WILAYAS });
  await prisma.commune.createMany({ data: COMMUNES });

  const products = PRODUCTS.map((p, i) => ({
    slug: p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') + '-' + i,
    name: p.name, price: p.price, oldPrice: p.oldPrice,
    color: p.color || '#000000', sku: p.sku,
    images: JSON.stringify(p.images),
    description: p.description,
    stock: Math.floor(Math.random() * 20) + 2,
  }));
  await prisma.product.createMany({ data: products });

  console.log(`✅ ${PRODUCTS.length} produits | ${WILAYAS.length} wilayas | ${COMMUNES.length} communes`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
